### ISSUE TITLE
Question: asynchronous functions after fast return of JSON?

### ISSUE THREAD

**Issue by Rainer-Kempkes** [trestletech/plumber#104]
hi,
in a realtime scenario, within a POST function I want to provide a result JSON as quick as possible. Afterwards, I want to do some archiving, cleaning up of tmp variables etc.
Within the POST function call, is it possible to calculate the result, return it and do some necessary, but not time critical work afterwards - f.e. with an asynchronous function call?

**Comment by trestletech** [comment]
Dup of https://github.com/trestletech/plumber/issues/95 please see the discussion there.
