### ISSUE TITLE
columns with NA values are dropped when return

### ISSUE THREAD

**Issue by kush99993s** [trestletech/plumber#112]
When in data frame, variable has NA value, it drops it,
example:

```
#* @get /returnNA
returnNA <- function(){
 data.frame(
        x = 1
        ,e = FALSE
        ,p = 0
        ,a = NA
        ,f = NA
        ,t = NA
        ,r1 = NA
        ,r2 = NA
        ,r3 = NA
        ,r4 = NA
        ,r5 = NA
      )
}
```

if I run following command, then response only contain column x,e,and p not others.
```
 curl "http://localhost:8000/returnNA"

[{"x":1,"e":false,"p":0}]
```

**Comment by trestletech** [comment]
Unfortunately this behavior is driven by the JSON serializer Plumber uses (`jsonlite`) and isn't something controlled in Plumber directly.

You can look at https://stackoverflow.com/questions/41965032/r-plumber-json-serializer-auto-unbox for an example of defining a custom serializer; I'm not sure if jsonlite exposes a parameter for controlling this behavior or not, unfortunately.
