### ISSUE TITLE
QUESTION: extracting params out of URL with req object fails

### ISSUE THREAD

**Issue by Rainer-Kempkes** [trestletech/plumber#127]
hi,
currently I'm struggling with extracting a param from the URL.
API-Call from CURL:
    curl localhost:8004/reward?eventid=xxxxxxxxxxxxxxxxxxxxxxx

with the param "eventid" in the URL.

In R the call is coming in and successfully proceeded. But req$eventid doesn't give back the param value of the calling URL, but NULL instead.
What am I doing wrong?
regards,
Rainer

**Comment by trestletech** [comment]
The argument won't be exposed on the request like that, but rather is made available as a parameter to the function that you're executing.

e.g.

```
#' @get /reward
function(eventid){
  print(eventid)
}
```

Now hit `/reward?eventid=1234` and you should see that the `eventid` parameter has been populated.

**Comment by Rainer-Kempkes** [comment]
works fine!
Thanks a lot!
Rainer
