### ISSUE TITLE
Cannot POST in UTF-8 under windows

### ISSUE THREAD

**Issue by jfdesomzee** [trestletech/plumber#153]
Hello,

I would like to use plumber for credit scoring in our platform. It works fine and it's supereasy. The only problem I've got is that the whole plateform is with UTF-8 encoding and special character are not passed properly.
I guess it's because I run plumber on a windows computer.

Here is an example of what's happening:

File D:/5-Testing/Plumber/test_accent_API.R:

#* @post /text

test_accent_API <- function(Json){
  save(Json,"D:/temp/Json.Rdata")
  return(c(Json$text,"Cécile"))
}

require(plumber)
r <- plumb("D:/5-Testing/Plumber/test_accent_API.R")

r$run(port=443)

![image](https://user-images.githubusercontent.com/26111904/28913629-04d1387a-7839-11e7-9b11-fb357643dc99.png)

If I look at the saved R object, we see that it has not been transmitted correctly

> load("D:/Temp/Json.Rdata")
> Json
$text
[1] "Ã©lise"

What I've tried:
* I tried to change default encoding options in R to UTF-8 but it did not work.
* I also tried in postman to specify the charset but it did not change anything either
![image](https://user-images.githubusercontent.com/26111904/28913678-2fb3f9ec-7839-11e7-8dba-1f7f5cbb2074.png)

Is there a way to specify the charset for the exchange?

Kind regards,

Jef

**Comment by FvD** [comment]
Yes this is a Windows thing. The lack of UTF-8 support also drives me crazy.

A solution that works consistently for me is to start your API in a Docker container, as [shown in the documentation](https://www.rplumber.io/docs/hosting.html#docker). I think that is the easiest solution to accept non-ascii on POST on a windows computer.

But if anybody else knows a solution for Windows please share! I have grown used to starting sessions on Windows with `options(encoding='UTF-8')` but that does not nearly solve all problems.

**Comment by FvD** [comment]
To my surprise my suggestion to deploy in a Docker container is not a solution at all. I usually build my Linux containers on a Linux machine. Out of curiosity I tried it on a Windows machine, building the image on Windows and then running it. All in-code accents look funny in the GET responses, just as you pointed out in your example! 

Stranger still, I then built the image on a remote environment, where I assume they build on Linux (Bluemix) and the problem was also there. I checked the local files on the windows machine and they are UTF-8 encoded. 

I have no access right now to a local Linux machine, but will verify as soon as I can that it does indeed work correctly there. In the meantime hopefully somebody else has an idea about what is happening here.

**Comment by jfdesomzee** [comment]
The problem is caused when UTF-8 “é” is literally interpreted as latin-1, that is 11000011 10101001 is read as the two 1-byte latin-1 characters Ã©, rather than the 2-byte UTF-8 character é

But how to tell the API that it is recieving UTF-8 and not latin-1?

**Comment by trestletech** [comment]
Sorry I'm just now getting to this. Unfortunately I don't have much insight as I don't have access to a Windows machine at the moment nor do I know a ton about encoding in R across different platforms.

**Comment by johanneswaage** [comment]
Any update on this? We have a hard time using plumber for commercial operations, since there is no support for Danish characters. All settings and strings are encoded as "UTF-8", but it still fails on Windows.

**Comment by jfdesomzee** [comment]
I just wrote a R function that transform the unproperly written characters and I apply it to the recieved parameters. Certainly not the best option but it does the job for now. 


str_replace_wrong_utf8 <- function(String) {
 str_replace_all(String,c("Ã©"="é",
                          "Ã¨"="è",
                          "Ãª"="ê",
                          "Ã«"="ë",
                          "Ã¹"="ù",
                          "Ã¼"="ü",
                          "Ã§"="ç",
                          "Ã¢"="â",
                          "Ã "="à",
                          "Ã®"="î",
                          "Ã´"="ô",
                          "Ã¶"="ö",
                          "Ã¤"="ä",
                          "Ã»"="û",
                          "Ã‹"="Ë",
                          "ÃŠ"="Ê",
                          "Ã‚"="Â",
                          "Ã„"="Ä",
                          "Ã”"="Ô",
                          "Ã–"="Ö",
                          "Ã›"="Û",
                          "Ãœ"="Ü"))
}

**Comment by johanneswaage** [comment]
Thanks for the hack, we also implemented something very similar. Let’s hope for a real fix for plumber, which otherwise works great

**Comment by farrjere** [comment]
@trestletech are you okay with assuming the request body and the response body are encoded in UTF-8?

**Comment by trestletech** [comment]
That's sounds like a reasonable assumption. I've marked this one as `help needed` as I a.) don't have access to a Windows machine to develop/test a fix, and b.) am not terribly well versed in encoding issues. UTF-8 only sounds like a reasonable expectation in more controlled environments; I'm not sure if that's a globally safe assumption for a networked service, though.

**Comment by schloerke** [comment]
Using github master.

In the first window...
```
tmp <- tempfile("utf8_test")
cat(file = tmp, "
#' @post /text
test_accent_API <- function(input) {
  str(input)
  return(c(input$text, 'Cécile'))
}
")
plumber::plumb(tmp)$run(port = 12345)
```

In another window...
```
post_query <- httr::POST(
  "127.0.0.1:12345/text", 
  body = list(input = list(text = "working!")), 
  encode = "json"
)
httr::content(post_query)
#> [[1]]
#> [1] "working!"
#> 
#> [[2]]
#> [1] "Cécile"
```
