### ISSUE TITLE
How to access header where there "-" in names

### ISSUE THREAD

**Issue by kush99993s** [trestletech/plumber#155]
I am trying to pass header "X-Name" from postman then access it from API which is build using Plumber R.

However, I am not able to access it. using following code,

`req$HTTP_X-NAME`,  then i am getting following error.

> Error in (function (id, time_frame, req, res) : object 'name' not
> found\n"

If I use following code, I get NULL values,

    req$HTTP_X_NAME  

or 

    req[["HTTP_X-NAME"]

or 

    req[["HTTP_X-Name"]

Following is my code:

    #* @get /
    healthCheck <- function(){
      print("It's Running")
    }
    
    #* @param id:int Random Number
    #* @post /test/values
    #* @get /test/values
    test <- function(id, req, res){
      print(req[["HTTP_X-Name"]])
      return(req[["HTTP_X-Name"]])
    }

**Comment by trestletech** [comment]
Hi. This is working for me. The proper name is all-caps with hyphens substituted for underscores like you have in your second example.

```
#* @get /
healthCheck <- function(){
  print("It's Running")
}

#* @param id:int Random Number
#* @post /test/values
#* @get /test/values
test <- function(id, req, res){
  print(ls(req))
  print(req[["HTTP_X_NAME"]])
  return(req[["HTTP_X_NAME"]])
}
```

Then I can run

```
$ curl --header "X-Name: hithere" http://localhost:9824/test/values
["hithere"]
```

**Comment by kush99993s** [comment]
Thanks, it is working for me 👍
