### ISSUE TITLE
browser always shows cannot display this page

### ISSUE THREAD

**Issue by feiyangdou** [trestletech/plumber#158]
Thanks a lot for developing this great package!

I just start playing with it, I copied the example in the readme section and the terminal version worked perfect but when I tried the browser, it showed cannot display this page. I'm still new to this so I was wondering if I missed any parts. Does anyone have any thoughts what could be the potential problems? 

Thanks!

**Comment by trestletech** [comment]
Can you provide some additional details? What are the contents of the file you're trying to plumb? What commands are you running to run Plumber? How are you accessing the API when it works on the "terminal version", and what URL are you visiting when it doesn't work in the browser?

**Comment by trestletech** [comment]
Closing due to lack of response. Please reopen if you're still seeing an issue.
