### ISSUE TITLE
Wrong filename in Docker introduction + no `tail` method

### ISSUE THREAD

**Issue by romatik** [trestletech/plumber#159]
In section **7.3.1 Default Dockerfile** the command to start the server is said to be:
`docker run --rm -p 8000:8000 trestletech/plumber /usr/local/lib/R/site-library/plumber/examples/04-mean-sum/meansum.R`
However, name of the file has been changed to `plumber.R`, so instead it should be:
`docker run --rm -p 8000:8000 trestletech/plumber /usr/local/lib/R/site-library/plumber/examples/04-mean-sum/plumber.R`
Then everything is fine when starting the service.

In the same section there is a reference to `tail`:

> The /tail path is one that’s defined in the plumber file we just specified – you should get an empty array back (`[]`).

There is no `tail` method in the `plumber.R` file, so instead this section should be about `mean` method that is, indeed, defined.

**Comment by trestletech** [comment]
Thanks for pointing this out! Fixed in the docs and the Docker image.
