### ISSUE TITLE
Inconsistent plumbr vs plumber naming

### ISSUE THREAD

**Issue by daattali** [trestletech/plumber#17]
Hey Jeff, just a heads up that it looks like you advertised on twitter a URL of http://plumbr.trestletech.com/ and in the tagline description of this repo you're also using the same url, but it's a 404 because of plumber vs plumbr.

I see there was a commit "Renamed to plumbr." so I suppose you intended to call it plumbr and ended up going with plumber? Anyway, just thought you should fix the URLs

**Comment by trestletech** [comment]
Thanks! Just fixed it. Turns out there was already a "plumbr" that I managed to overlook in the first rename, so I landed here.
