### ISSUE TITLE
Is plumber multithreading or single threading ?

### ISSUE THREAD

**Issue by kush99993s** [trestletech/plumber#170]
Hi,

I was wondering if you can provide little more information about plumber infrastructure ?

Is it single threading or multithreading ?

**Comment by trestletech** [comment]
R is single threaded, so Plumber is as well. For future searchers, this type of information will eventually be documented here: https://www.rplumber.io/docs/runtime.html (but it's mostly empty now).

Plumber currently can only handle one request at a time. Meaning that if you have an endpoint or filter that takes 5 seconds to return, all other requests are blocked and inactive for those 5 seconds. This is why it's important to load balance across multiple R processes if performance or availability is important to your API. (Discussed [here](https://www.rplumber.io/docs/hosting.html)). 

There's talk about incorporating Promise-based handling into Plumber now that these asynchronous features are being developed in the underlying `httpuv` package. But there are no definite plans there yet.
