### ISSUE TITLE
do_provision() can't finish installing

### ISSUE THREAD

**Issue by brettkobo** [trestletech/plumber#175]
When I am using do_provision() I am able to connect to Digital Ocean but I get stuck half way through the install.

I get:
```
A new version of /boot/grub/menu.lst is available, but the version installed 
currently has been locally modified.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. show a 3-way difference between available versions
  6. do a 3-way merge between available versions (experimental)
  7. start a new shell to examine the situation

What would you like to do about menu.lst? 
```

I can't send any commands through the R console, so I am unable to finish the installation.

**Comment by trestletech** [comment]
Can you send the output of `packageVersion("plumber")` and the exact command you're running to provision the machine? Is it just a plain `do_provision` or are you passing in an existing Droplet that you're trying to provision?

**Comment by Chidiebube** [comment]
I experienced this same issue when using packer and a shell provisioner to spin up an image on Digital Ocean. Upgrading the image version from "ubuntu-**16**-04-x64" to "ubuntu-**17**-04-x64" in my packer `template.json` file solved it for me.
