### ISSUE TITLE
IE10 IE11 - API with root definition deployed to Connect asks to download JSON file

### ISSUE THREAD

**Issue by joncfoo** [trestletech/plumber#177]
1. Deploy the following `plumber.R` file to Connect:

```R
#* @get /
root <- function(){
  "hello world!"
}

#* @get /mean
normalMean <- function(samples=10){
  data <- rnorm(samples)
  mean(data)
}
```

2. Open the deployed API in Connect
3. Note that IE10 & IE11 ask to download a JSON file instead of displaying `["hello world!"]`

IE Edge, Chrome, and Firefox correctly display the root content: `["hello world!"]`

**Comment by trestletech** [comment]
All the results I can find on this front involve hacking the registry. It doesn't seem like there's a consistent way to tell older IEs that they should display rather than download JSON. 

Closing as wontfix unless somebody else knows better.
