### ISSUE TITLE
Question: Any other good resources or examples of plumber in production to study?

### ISSUE THREAD

**Issue by vfulco** [trestletech/plumber#178]
I have done the obligatory goog search with a very wide net finding some stuff.  Still in noob phase especially as I deal with rendering automated reports and delivering them (either on screen or email).

Some marvelous work done at these links:

1. https://www.knowru.com/blog/how-create-restful-api-for-machine-learning-credit-model-in-r/ 

This is actually a great 4 part series talking about APIs, basic setup, scaling with Docker, hosting on AWS.

2. https://romain.rbind.io/blog/2017/07/29/a-fortune-slack-slash-command-using-plumber/ The amazing contributor Romain Francois had this one integrating slack

3. https://www.computerworld.com/article/3171766/application-development/how-to-create-your-own-slack-bots-and-web-apis-in-r.html Computerworld's Sharon Machlis'  slack bot example

Github is kinda bereft of good study material.  TIA

**Comment by trestletech** [comment]
A couple of others to add to your list:

 - Mango Solutions detailed an engagement in which they leveraged Plumber here: https://www.mango-solutions.com/blog/production-r-at-ons
 - Kelly O'Briant gave a nice talk on infrastructure for R (and how they use Plumber as a piece of this) here: https://www.youtube.com/watch?v=WgIGM6yn3HA&feature=youtu.be I believe she's giving a refreshed version of this talk at the WiDS 2017 conference in the coming weeks.

Depending on what you're after, you may also find the [Hosting](https://www.rplumber.io/docs/hosting.html) and [Security](https://www.rplumber.io/docs/security.html) chapters of the documentation useful.

**Comment by vfulco** [comment]
Excellent. Thanks.  Need to drill down into securing.  Party of my issue is I am relying on upstream services (Typeform and Mailgun) to deliver inputs and don't have the ability to pre-authorize users.

**Comment by vfulco** [comment]
FWIW: another great writeup on what is possible: https://raybuhr.github.io/2017/10/making-predictions-over-http/

**Comment by mxblsdl** [comment]
For people following plumbr I found this article useful:
https://medium.com/tmobile-tech/using-docker-to-deploy-an-r-plumber-api-863ccf91516d
