### ISSUE TITLE
ggplot2 gives error, is it supported? 

### ISSUE THREAD

**Issue by koaning** [trestletech/plumber#18]
I have the following `post_serv.R` file. 

```
# post_serv.R

library(ggplot2)
library(magrittr)

df <- data.frame(x = rnorm(10, 0, 1), y = rnorm(10, 0, 1))

#' @png
#' @get /plot
get_plot <- function(){
  ggplot() + geom_point(data=df, aes(x,y), alpha = 0.5)
  # plot(df$x, df$y, main="Recent Values")
}
```

This then gets run from Rstudio using `plumber::plumb('~/Desktop/post_serv.R')$run(port=8000)`

Then when I access via the browser I get this error: 

```
{"error":["500 - Internal server error"],"message":["cannot open the connection"]}
```

When I use the standard `plot` function, everything seems to work just fine. Is ggplot2 not supported?

**Comment by gaborcsardi** [comment]
MAybe you just need to `print()` the plot?

**Comment by koaning** [comment]
d0h. sgould have seen that one coming. thanks!

**Comment by nguyen-dhn** [comment]
> MAybe you just need to `print()` the plot?
4 years later and it has just made me spend several days finding out what the solution is. THanks a lot!
