### ISSUE TITLE
Mailgun Parsed Message Parameters?

### ISSUE THREAD

**Issue by vfulco** [trestletech/plumber#184]
Modding the example mailgun.R, should I expect access to all variables forwarded by MG found on this page?

http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#routes

I tried to include the stripped-text, email body and got 'stripped' error

Code--
```
#* @post /mail
function(from, subject, body){
  emails <<- rbind(emails,
                 data.frame(from=from,
                        time=date(),
                        subject=htmltools::htmlEscape(subject),
                        body=htmltools::htmlEscape(stripped-text),
                        stringsAsFactors=FALSE))
  TRUE
}
  ```
Error--
```
Loading required package: htmltools
2017-10-17T15:16:59.152942412Z app[web.1]: Starting server to listen on port 8006
2017-10-17T15:19:19.771869676Z app[web.1]: <simpleError in grepl(pattern, text, useBytes = TRUE): object 'stripped' not found>
```

TIA

**Comment by trestletech** [comment]
There's a bug in your R code. `body=htmltools::htmlEscape(stripped-text),` is trying to subtract the variable `text` from the variable `stripped`. Neither of which exist.

**Comment by vfulco** [comment]
Hi-  the term "stripped-text" is a label used by MG in the parameters list they deliver when they forward emails to HTTP.  Is there a separate source of "fields" for lack of a better word that plumber accepts?

Separately when I try the example code I get no "from:" information.  TIA.

**Comment by trestletech** [comment]
Oh. Then you might need to put the variable name in backticks. But I'm not sure if R will allow even that for a variable name.

You can try accessing this property on the `req$args` list if you're unable to inject it as a parameter.

**Comment by vfulco** [comment]
Great, will give it a try!  Separately submitted a bunch of PRs to lightly edit the online documentation.  Should be quick approvals.  Thanks for everything.
