### ISSUE TITLE
How to load a package when launching with doker

### ISSUE THREAD

**Issue by artpulsion** [trestletech/plumber#188]
Hi, my name is Sofiane, i'm student in Paris and very interested about R and what we can do with it.
First of all, I want to thanks you for all your job related to plumber it's help me a lot and everything works perfectly, thank you so much !

I'm presently trying to improve my skills within the intersection of plumber, R package/scripts and docker.
Based on this documentation (https://www.rplumber.io/docs/hosting.html) my project is in the good way but now I'm faced to a problem.

I would like to know if there is a solution to tells at docker when we run a container to load a library when I run my command : 
`docker run -it --rm -p 8000:8000 -v `pwd`path_to_the_decorated_function:/plumber.R docker_image_name path_to_the_decorated_function
` 

Thanks you :)

**Comment by nuest** [comment]
You could

- mount an `.Renviron` file into the container to load the package for every R session by default
- overwrite the default command of the Docker image.

Can you post a reproducible example? Which image are you using?

**Comment by trestletech** [comment]
you should just be able to add a `library()` call into the `plumber.R` script or use either of the tips provided above. Closing for now unless we get a reproducible example explaining the problem.
