### ISSUE TITLE
Can we access request attributes?

### ISSUE THREAD

**Issue by Ironholds** [trestletech/plumber#19]
Is it possible to access attributes such as the user's IP address or user agent in plumber code?

**Comment by trestletech** [comment]
Sure. plumber uses httpuv which follows the [rook API](https://github.com/jeffreyhorner/Rook#the-environment), so you just need to accept the `req` argument in your function and then grab the element off of it.

```
#' @get /mean
normalMean <- function(samples=10, req){
  print(req$HTTP_USER_AGENT)
  data <- rnorm(samples)
  mean(data)
}
```

**Comment by Ironholds** [comment]
Awesome; thanks!
