### ISSUE TITLE
Question - multiple requests at a time?

### ISSUE THREAD

**Issue by lautiamkok** [trestletech/plumber#190]
I just have a question on plumber - does it serve multiple requests at a time?

We have been using Shiny open source version for a few years but the [problem with it is that it only server one request at a time](https://www.r-bloggers.com/shiny-server-open-source-edition-solution-for-cpu-bound-apps/):

> if one user is doing some calculation, the other user must wait until that process finished!

It seems that it has the same limitation with [jug](https://github.com/Bart6114/jug) too. Hence it has a plugin on top called [jug.parallel](https://github.com/Bart6114/jug.parallel).

What about plumber then?

**Comment by dselivanov** [comment]
Same about plumber - check the [docs](https://www.rplumber.io/docs/runtime.html#performance-request-processing). You can spawn multiple plumber services and use some load balancer like nginx or haproxy.

**Comment by trestletech** [comment]
Eventually I'm hoping to incorporate the new asynchronous work that the Shiny team has been doing as the approach for mimicking parallel functionality in plumber. But I'm going to let it soak in httpuv for a bit first then will start thinking through the work on plumber's end.
