### ISSUE TITLE
Question: Nuxt or Angular + Plumber?

### ISSUE THREAD

**Issue by lautiamkok** [trestletech/plumber#193]
After a few years of using Shiny and we have had lots of issues with it, e.g. it is too opinionated and it does not support concurrent requests on the open source version.

Plumber seems to be an alternative to Shiny but its documentations seems incomplete in many parts, e.g. [CORS](https://www.rplumber.io/docs/security.html#cross-origin-resource-sharing-cors)

It seems to suggest that CORS is viable with Plumber. If so, how do we enable that in our API?

We would like to use Plumber as an API to create endpoints and use [Nuxt](https://nuxtjs.org/) or [Angular](https://universal.angular.io/) to send the requests, so we need CORS.

**Comment by trestletech** [comment]
Collapsing into #66 as that's where I plan to handle the CORS work.

FYI if you wanted to serve the Angular app via Plumber so you worry less about CORS, here's a model (using Vue.js) https://github.com/trestletech/movies-plumber

**Comment by lautiamkok** [comment]
@trestletech thanks for the links. 

I have integrated it with Nuxt which is the server-side of Vue:

https://github.com/lautiamkok/nuxt-plumber
