### ISSUE TITLE
Question:  Mailgun email as output?

### ISSUE THREAD

**Issue by vfulco** [trestletech/plumber#196]
Assuming some protections are in place through filtering, is there any reason why hitting an endpoint can't trigger an email?  I am thinking along the lines:

1. Email reaches mailgun
2. Auto-forward to plumber endpoint
3. Processed 
4. Results emailed out in html or rmd back to original sender

TIA.

**Comment by trestletech** [comment]
Shouldn't be an issue. You'd just use plumber for step 2 to give Mailgun a way to communicate with R. Outside of that it would just be a matter of configuring R to use the mailgun API to process and send the appropriate emails.

**Comment by vfulco** [comment]
Terrific to hear.  I am just a solo-entrepreneur working on some new, not-ready-for-primetime apps.  What can I do for you Jeff besides say "thank you"?
