### ISSUE TITLE
Gracefully clean up db connections

### ISSUE THREAD

**Issue by rundel** [trestletech/plumber#198]
After looking over the documentation I cannot find a way of cleaning up a dbConnect / pool that I've established at the start of a script. Is there any functionality for something equivalent to `on.exit` for plumber?

**Comment by trestletech** [comment]
Great idea!

Fixed in #200 and now documented here https://www.rplumber.io/docs/runtime.html#exit-handlers

**Comment by rundel** [comment]
Thanks, I'll check it out this evening
