### ISSUE TITLE
Weird amount of slowness?

### ISSUE THREAD

**Issue by Ironholds** [trestletech/plumber#20]
So I've been working on a project at https://github.com/Ironholds/sharder (it should be self-contained and locally runnable). You launch it and then run:

> readLines("http://localhost:8000/mirror?https=0")

It's exceedingly slow to produce a response, so I filled it with little debugging flags (producing periods, printing timestamps, all the rest) and...none of them are slow. They churn through incredibly quickly. It does everything in main() in a fraction of a second. But for some reason it's incredibly slow to actually return and send out a response - as proof, I typed out this entire comment in less time than it took to run.

Any ideas?

**Comment by trestletech** [comment]
I noticed that if I comment out lines 28-30 of core.R and access it from the browser, I don't get that same slowness, so I'm suspecting there's a buffering issue with readlines. But I have yet to confirm.

**Comment by trestletech** [comment]
Likewise, on the unaltered file:

```
> system.time(httr::GET("http://localhost:8000/mirror?https=0"))
   user  system elapsed 
  0.006   0.001   2.412 
>  # (The first run)
> 
> system.time(httr::GET("http://localhost:8000/mirror?https=0"))
   user  system elapsed 
  0.005   0.001   0.014 
>  # (Subsequent runs)
```

**Comment by trestletech** [comment]
Confirmed on wireshark that the `readLines` request is getting an HTTP 200 in < 0.1s. It's just some quirk of `readLines` that makes it continue waiting for additional input after the HTTP response has already terminated. You may need to drop to a lower-level connection to read from.

Another hack that works:
```
> system.time(readLines("http://localhost:8000/mirror?https=0", 1))
   user  system elapsed 
  0.000   0.000   0.052 
> 
```

Closing this for now. Feel free to reopen if you see something pointing at plumber as the source of unexpected slowness.

**Comment by Ironholds** [comment]
Huh, cool! Thanks for the fix :)
