### ISSUE TITLE
Digital Ocean Setup

### ISSUE THREAD

**Issue by Btibert3** [trestletech/plumber#207]
I am attempting to follow along with the docs for DO located `https://www.rplumber.io/docs/hosting.html#digitalocean`

I have confirmed that I can interface with DO using `analogsea`.   After running `mydrop = plumber::do_provision()`

I see output similar to below (truncated, the tail)

```
Rules updated
Rules updated (v6)
Firewall is active and enabled on system startup
Created symlink from /etc/systemd/system/multi-user.target.wants/plumber-hello.service to /etc/systemd/system/plumber-hello.service.
● plumber-hello.service - Plumber API
   Loaded: loaded (/etc/systemd/system/plumber-hello.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-11-13 02:37:23 UTC; 4s ago
 Main PID: 16697 (R)
   CGroup: /system.slice/plumber-hello.service
           └─16697 /usr/lib/R/bin/exec/R --slave --no-restore -e pr~+~<-~+~plumber::plumb('/var/plumber/hello/plumber.R');~+~~+~pr$run(port=8000)

Nov 13 02:37:23 Judeo-ChristianAversion systemd[1]: Stopped Plumber API.
Nov 13 02:37:23 Judeo-ChristianAversion systemd[1]: Started Plumber API.
Nov 13 02:37:24 Judeo-ChristianAversion Rscript[16697]: Starting server to listen on port 8000
```

When I attempt to hit `<IP>:8000`, I am getting timeout errors.  

This package looks fantastic.  I am sure it's something to do on my end, but I am not really sure where to start debugging this after multiple attempts.

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.3.1      analogsea_0.5.0 plumber_0.4.2   readr_1.1.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13   crayon_1.3.4   R6_2.2.2       jsonlite_1.5   magrittr_1.5   rlang_0.1.4    stringi_1.1.5  curl_3.0      
 [9] rstudioapi_0.7 tools_3.4.2    hms_0.3        httpuv_1.3.5   yaml_2.1.14    compiler_3.4.2 tibble_1.3.4  
```

**Comment by Btibert3** [comment]
Closing this myself.  This was part user-error and part process.

1.  Created a droplet with `do_provision` without a droplet named
2.  The step above, more often than not, would result in a Port 22 error.  I would reference the drop created in step 1 and re-submit `do_provision` with that id and unstable=TRUE.
3.  Referencing the url, without the port, worked fine.
4.  I pushed my local api to the server with something like `do_deploy_api(mydrop, "plumbertest", "./api", 8001)`.  This exposed an my routes at <url>/plumbertest/....

This is great.  A bit of a learning curve, but excited to be up and running with some demo code!

**Comment by trestletech** [comment]
Can you expand on "would result in a Port 22 error." What was the error message you were seeing there?

As you might have guessed, this is supposed to work on the first try...

**Comment by Btibert3** [comment]
As luck would have it, I now can not replicate the error, though I am getting this.

```
Error in sample(x, size = 1) : object 'adjectives' not found
```

with the following info

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plumber_0.4.2

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  magrittr_1.5    R6_2.2.2        tools_3.4.2     analogsea_0.5.0 rstudioapi_0.7  curl_3.0       
 [9] yaml_2.1.14     Rcpp_0.12.13    crayon_1.3.4    stringi_1.1.5   jsonlite_1.5    httpuv_1.3.5   
```

**Comment by trestletech** [comment]
Hm. I actually saw a similar issue from analogsea in https://github.com/sckott/analogsea/issues/125

**Comment by trestletech** [comment]
Also I just increased the artificial delay I have before a droplet is deemed "started". I've seen similar messages recently, so maybe DO is returning a "started" event earlier than they used to or machines are slower to get network access for some reason. We'll see if that helps. https://github.com/trestletech/plumber/commit/0a6df497d43f1b4b5443967f6fa069b2a37d7006

**Comment by Btibert3** [comment]
That seemed to have done it.  First attempt, looks good.  Thanks for this.
