### ISSUE TITLE
Implement sessions using secure cookies

### ISSUE THREAD

**Issue by trestletech** [trestletech/plumber#21]
A la http://flask.pocoo.org/docs/0.10/quickstart/#sessions

**Comment by JFJanssen** [comment]
This would be a -great- feature!

**Comment by trestletech** [comment]
Currently blocked by the lack of a good encryption library for R. The best I know of is the PKI package which has a limit of ~200 bytes. If a better one exists or is created, I'd love to hear about it!

**Comment by trestletech** [comment]
https://gist.github.com/trestletech/69b559016d74ff2fe430

**Comment by trestletech** [comment]
https://github.com/jeroenooms/sodium/blob/master/R/simple-encrypt.R
