### ISSUE TITLE
Swagger Output

### ISSUE THREAD

**Issue by Btibert3** [trestletech/plumber#211]
I was able to generate swagger output, which is fantastic.  I am very new to this, but the responses object only appears to have a default response, and not something that defines the output.  Example below.

[Salesforce Example](https://help.salesforce.com/articleView?id=external_services_schema.htm&type=0)

When I expose `__swagger__` to Salesforce, everything passes.  I know that this is piece is related to Salesforce, but it appears that they are looking for a definition of a 200 response and a name for that response.

Again, I am a bit out of my depth, but just from poking around swagger documentation quickly, it does seem that Swagger allows the resources to be defined.  Is it possible that we can decorate our functions within R to populate these values?

Thanks again for this fantastic package.

**Comment by trestletech** [comment]
Hi. I'm not clear what you mean by 

> Swagger allows the resources to be defined

I do have some (undocumented 😔) flags that you can use to control the Swagger output for your endpoints. But I don't see anything about "resources" in [the Swagger spec](https://swagger.io/specification/). Can you clarify what parts of the Swagger Schema you're missing?

**Comment by Btibert3** [comment]
I am still new to this, but here is my best shot on explaining it.  

Here is the swagger docs created by plumber for my basic API:

[https://gist.github.com/Btibert3/57f84601daf4771831b81a61b24f09b0#file-plumber-swagger-example-json-L19](https://gist.github.com/Btibert3/57f84601daf4771831b81a61b24f09b0#file-plumber-swagger-example-json-L19)

In my file, the `responses` area is just default text.  

From a blog post that inspired my idea to use plumber, you can see that response area has more information beyond "default"

[https://github.com/afawcett/asciiartservice/blob/master/api/swagger/swagger.yaml#L41](https://github.com/afawcett/asciiartservice/blob/master/api/swagger/swagger.yaml#L41)

This is all still new to me, but my point is that Salesforce didn't recognize my output but did parse the Swagger inputs to my endpoint.  

When comparing my Swagger file to the example in the blog post, my gut is that it has to do with the information in the response area (show a 200 response, a schema with a reference, etc.) which is why I opened this ticket.  That said, perhaps there is more to it than that.

Thanks again.

**Comment by trestletech** [comment]
Check out the example at https://github.com/trestletech/plumber/blob/master/inst/examples/11-car-inventory/plumber.R#L16 . That allows you to give textual descriptions of the possible responses that your function could generate.

But I do not have the ability to define pointers to schemas that are defined elsewhere as you give in your example. I've thought about someday supporting that with R6 objects or something, but I'm not really sure how I'd go about it. Do you need to describe the full schema or is giving a textual explanation enough?

**Comment by Btibert3** [comment]
Doubling back on this while on vacation, this does the trick for now I believe.  Some really good examples in the code.
