### ISSUE TITLE
Support for negative numbers

### ISSUE THREAD

**Issue by etiennebr** [trestletech/plumber#212]
It seems like providing a negative number is not mapped to a `numeric`.

For instance:
``` r
#' @get /type/<x:numeric>
function(x){
  list(
    value = x,
    type = typeof(x)
  )
}
```
Then `curl https://localhost/type/-1.2` returns `{"error":["404 - Resource Not Found"]}`. Would changing the regex for numeric from `\d*\.?\d*` to `-?\d*.\d*` break anything? Also, since the numeric wasn't working I tried to receive `x` as character and parse it within the code, but dots(`.`) are explicitly excluded by `[^\./]+`. Would it be possible to allow dots in characters?

**Comment by trestletech** [comment]
Closed by #213
