### ISSUE TITLE
allow used ports

### ISSUE THREAD

**Issue by verajosemanuel** [trestletech/plumber#217]
I have more than one plumber script besides some flask apis built with python.
The issue is the only opened port I can use is 80 (the usual port for web apis).
Plumber does not allow me to run any other service if port is used. This is not the usual behavior for web services.

**Comment by trestletech** [comment]
This is unfortunately how ports behave -- only one process can listen at a time.

That being said, you could look at using nginx or apache on port 80 and having it proxy traffic to other internal ports where Flask or Plumber is listening.
