### ISSUE TITLE
Error: Multiple @serializers specified for one function

### ISSUE THREAD

**Issue by McCompexpert** [trestletech/plumber#223]
Trying to replicate the code in this post:

[building-your-own-blockchain-in-r](https://www.r-bloggers.com/building-your-own-blockchain-in-r/)

```
Error in stopOnLine(lineNum, line, "Multiple @serializers specified for one function.") : 
  Error on line #95: '#* @serializer custom_json' - Multiple @serializers specified for one function.
```
The error occurs at executing of this line: 

`r <- plumb('blockchain-node-server.R')`

Full code:
```
list.of.packages <- c("plumber","jsonlite")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
 
require(plumber)
require(jsonlite)
 
custom_json <- function(){
  function(val, req, res, errorHandler){
    tryCatch({
      json <- jsonlite::toJSON(val,auto_unbox=TRUE)
 
      res$setHeader("Content-Type", "application/json")
      res$body <- json
 
      return(res$toResponse())
    }, error=function(e){
      errorHandler(req, res, e)
    })
  }
}
 
addSerializer("custom_json",custom_json)
# Make sure you put the path to your blockchain-node-server.R script
r <- plumb('blockchain-node-server.R')
r$run(port=8000)

```

Session Info:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plumber_0.4.4 uuid_0.1-2    httr_1.3.1    jsonlite_1.5  digest_0.6.13

loaded via a namespace (and not attached):
[1] compiler_3.4.0 R6_2.2.2       tools_3.4.0    rstudioapi_0.7 Rcpp_0.12.13   crayon_1.3.4   stringi_1.1.5  httpuv_1.3.5  
```

**Comment by trestletech** [comment]
Please provide the complete `blockchain-node-server.R` file, too. Without that I'm not sure what line 95 is.

**Comment by McCompexpert** [comment]
Sure, it is the file from this repository [rblockchain](https://github.com/jbernabe/rblockchain)

**Comment by trestletech** [comment]
There are two serializers defined on that chunk. https://github.com/jbernabe/rblockchain/blob/master/blockchain-node-server.R#L95-L97

`@html` and `@serializer ` contradict. You'll need to pick one output format for the function.

**Comment by McCompexpert** [comment]
Yep, deleted `@html` and it works now. Thank you!

**Comment by aegerton** [comment]
Sorry, @McCompexpert, how exactly did you resolve this issue, please?  I am still trying to figure it out.  Please excuse my ignorance...

**Comment by McCompexpert** [comment]
@aegerton - Just deleted `@html` in line 97, see [blockchain-node-server.R](https://github.com/jbernabe/rblockchain/blob/master/blockchain-node-server.R#L95-L97)

**Comment by aegerton** [comment]
Thank you @McCompexpert
