### ISSUE TITLE
using plumber package in Rscript and running script from cmd

### ISSUE THREAD

**Issue by nerdykamil** [trestletech/plumber#225]
In my Rscript (run.R):

`library(plumber)
r <- plumb("script.R")
r$run(host="127.0.0.1",port=8000)`

if I run the above code using RStudio or R console it works fine and gives me access after following output:

`Starting server to listen on port 8000 Running the swagger UI at http://127.0.0.1:8000/swagger/`

but when I try to run the same code as a .R file using Rscript, R CMD BATCH,R < run.R, pm2 it gets stuck at;

`Starting server to listen on port 8000`

and on accessing address I get 404: Resource Not Found Error. Also, note that I want to run this on windows therefore didn't try littler. Any idea, what I am doing wrong here or what might be the issue. Thanks!

**Comment by nuest** [comment]
The message it get "stuck" at is actually the right message. Can you post a reprex with your script and the exact address you try to access?

**Comment by nerdykamil** [comment]
@nuest, thats exactly my point it prints the right message but after that it is suppose to print 

> Running the swagger UI at http://127.0.0.1:8000/swagger/
which it doesn't therefore I am saying it gets stuck. I access http://127.0.0.1:8000/swagger/ but it gives me resource not found error.

**Comment by trestletech** [comment]
Cross posted here: https://stackoverflow.com/questions/48048155/using-plumber-package-in-rscript-and-running-script-from-cmd

Answer was:

`run` takes a `swagger` argument that defaults to `interactive()`. i.e. it only enables swagger if you're running interactively.

You can hardcode this to `TRUE` if you want Swagger to be enabled on your router even when run programmatically.

```
r$run(host="127.0.0.1", port=8000, swagger=TRUE)
```
