### ISSUE TITLE
Multiple get requests for same script

### ISSUE THREAD

**Issue by FinScience** [trestletech/plumber#227]
Hi,

I have multiple APIs in R which I want to host through same port. On trying the following, the server is not starting. Could you please let me know of an alternative to run multiple APIs from same port.

```
# context_extraction.R

#* @get /sum_data

context_extractor = function(res, req,cr_num,mnem){

.........
return(df)
}

#* @get /func_trav

combo_viz = function(res, req,mnem,funcs){

.........

return(rf

}


```

**Comment by trestletech** [comment]
See https://www.rplumber.io/docs/programmatic-usage.html#mount-static

You'll want to create two plumber routers and then compose them by mounting them at some unique URL path on the parent router. Then have the parent router actually be the one running/listening on the port.
