### ISSUE TITLE
Return HTML widgets from r viewer 

### ISSUE THREAD

**Issue by chinthanishanth** [trestletech/plumber#229]
datatable from DT PACKAGE and  graphs from PLOTLY PACKAGE which are HTML widgets seen from  R viewer pane,  i want to send them as response from incoming requests, may i know  how to do it... Currently there is support for graphs using @png,@jpeg... But how to return HTML widgets from r viewers pane as json response ... Any Help is appreciated...

**Comment by trestletech** [comment]
`@serializer htmlwidget`, see https://www.rplumber.io/docs/rendering-and-output.html#serializers

**Comment by chinthanishanth** [comment]
Thanks Jeff, for your response, i have implemented it.
