### ISSUE TITLE
let a few services continuously running (daemon) using plumber.

### ISSUE THREAD

**Issue by sahilseth** [trestletech/plumber#23]
What would be the recommended way to create a daemon using plumber ?

```
## if plum is a script which contain all the commands
plum.R
## running from terminal using & should work
Rscript plum.R &
```

**issues**
Issue is what if I press this twice, and there are two conflicting scripts running on the same port.
What is someone else does the same.

Possible to check all plumber services running (given a port)?

**Comment by trestletech** [comment]
Thanks for opening this. This is something I'm actively thinking about. I don't think the solution belongs in plumber, since R's forte is not load balancing and managing processes, but I have a poked around at a couple of other tools that can be used to accomplish at least some of these purposes. I'll get them written up shortly.

**Comment by trestletech** [comment]
I've started writing this up here: http://plumber.trestletech.com/docs/hosting/

**Comment by Rauno56** [comment]
I personally solved this creating bash-script `runServer` as
```bash
#!/bin/bash

port=${1:-9002}

kill $(ps aux | grep "$port" | grep plumb | awk '{print $2}')
R --vanilla -e "library(plumber); pr <- plumb('query.api.r'); pr\$run(port=$port)"
```
The file `query.api.r` has all the annotated definitions there without actually running any `plumber` code. It's good for testability:
```r
#* @get /gimmeTrue
api.gimmeTrue <- function () {
  TRUE
}
```
so running several services is as simple as:
```bash
./runServer 9000 && ./runServer 9001
```
or use a process manager: pm2 has `--interpreter`, nodemon `-x` flag for that.

**Comment by trestletech** [comment]
Between the above link and http://plumber.trestletech.com/docs/docker/, I'm calling this closed.
