### ISSUE TITLE
Hooks do not modify "value"

### ISSUE THREAD

**Issue by uipo78** [trestletech/plumber#232]
According to section 8.4 of the documentation:
>One feature when defining hooks in Plumber routers is the ability to modify the returned value. The convention for such hooks is: any function that accepts a parameter named value is expected to return the new value. This could be an unmodified version of the value that was passed in, or it could be a mutated value. But in either case, if your hook accepts a parameter named value, whatever your hook returns will be used as the new value for the response.

However, if I start up this:
```
router = plumber$new()
router$registerHooks(list(
     "postroute" = function(data, req, res, value) {
         return(list("msg" = "I'm not a number"))
     }
))
router$handle("POST", "/addAandB", function(req, res) {
     result = req$args$A + req$args$B  
     return(list("result" = result))
})
router$run()
```
and do
```
curl --data "{\"A\": 1, \"B\": 2}" http://127.0.0.1:6703/addAandB
```

Then this is returned 
```
{"result":[3]}
``` 
instead of 
```
{"msg":["I'm not a number"]}
```

This issue was encountered with plumber 0.4.4.

**Comment by trestletech** [comment]
Mea culpa! Can you try out the `value-forwarding` branch? 

```
devtools::install_github("trestletech/plumber", ref="value-forwarding")
```

**Comment by uipo78** [comment]
I received 

```{"msg":["I'm not a number"]}```

Perfect!
