### ISSUE TITLE
Deploy to my own Shiny Server

### ISSUE THREAD

**Issue by aleDsz** [trestletech/plumber#240]
Hi,

There's a way to deploy my API to Shiny Server? I'm hosting on Amazon and my Shiny apps are running properly, but I don't know how to host my R plumber API.

Thanks,
aleDsz.

**Comment by trestletech** [comment]
Sorry, Shiny Server doesn't currently support Plumber. I'm not sure of their plans there but feel free to open an issue on their repo: https://github.com/rstudio/shiny-server
