### ISSUE TITLE
How to load api (@serializer htmlwidget) into my own html?

### ISSUE THREAD

**Issue by shizidushu** [trestletech/plumber#254]
I want to create a api return htmlwidget and then use it in my own html/js file.

It is [easy to do the first part](https://github.com/trestletech/plumber/issues/79) with `@serializer htmlwidget`

I want to fetch the api and then load the htmlwidget into my html.

After searching with Google, I only find to use `iframe` or `object` tag to do it like the following.

```html
<object data="http://127.0.0.1:8000/plotly" width="100%" height="500" type="text/html"> </object>
```

But the ideal way in my mind to load it is:

- Using [vue framework](https://vuejs.org/) (optional)
- Send http request with [axios](https://github.com/axios/axios)
- Then load the result into html

I spend a lot of time to figure out it but without sucess. (I don't know much about html/javascript)

Can someone help me with this?

**Comment by shizidushu** [comment]
I find a better way to do with htmlwidget.

Extract `x` from the htmlwidget object then serve is as unboxedJSON. Finally, render it in javascript.

I just test it with `recharts` library but I guess this approach applies to other htmlwidget based library.

Thanks to [recharts document](https://recharts.cosx.org/interface). I got some idea about how a htmlwidget library was constructed after reading it.

```r
#' json 1
#' @serializer unboxedJSON
#' @get /json1
function(){
  library(recharts)
  require(plyr)
  
  series = list(list(
    name = 'Sales',
    type = 'bar',
    data = c(5, 20, 36, 10, 10, 20)
  ))
  # 定义坐标轴部分
  ext = list(
    xAxis = list(list( 
      data = c('shirt','cardign','chiffon shirt','pants','heels','socks')
    )),
    yAxis = list(list())
  )
  # 绘制
  p <- ePlot(series, ext)
  p$x
}
```

**Comment by brettkobo** [comment]
I was also having issue with this. Looked at a example that Jeff Allen [wrote](https://github.com/rstudio/webinars/tree/master/60-plumber/twilio) for his webinar on plumber.

Looks like an easy way is to create a empty <iframe> and then change the src to the API call. 

It would look something like this.

```
<html>
 <head></head>
   <body>
      <iframe id="da-iframe" width="100%"></iframe>
      <script>
        var frame = document.getElementById("da-iframe")
        iframe.src = "http://localhost:9999/cool-api-name"
      </script>
 </body>
</html
```

**Comment by shizidushu** [comment]
In my experience, it's easy to use <iframe> or <object> tag. But loading problem may occur if we integrate the htmlwidget into existing service, especially when the existing service is complex, such as asp.net. 

It's quickly to get the json part from api and then plot it using the corresponding JS library like plotly. And the generated HTML is usually very large and takes more time to fetch it.

**Comment by maheshKulkarniX** [comment]
[https://stackoverflow.com/a/56150308/10574296](url)
