### ISSUE TITLE
Plumber deploy error

### ISSUE THREAD

**Issue by sajukassim** [trestletech/plumber#256]
I have created a R Webservice and trying to deploy throgh  Plumber.
It works fine with localhost.
Now I want to use a public ip. I am getting the following error.

Please help

 r$run(host="104.197.250.128", port=8080)
Starting server to listen on port 8080
Running the swagger UI at http://104.197.250.128:8080/__swagger__/
Error in startServer(host, port, app) : Failed to create server

**Comment by sajukassim** [comment]
Thanks it works with host="0.0.0.0" and can access the service outside..

Now the service is  stopped  if I stopped in R studio. How can I keep the service on all the time so that the request can be accepted. I read  pm2 can be used.

Can you please help...

**Comment by chakhalyan1** [comment]
Hi I also get the first error Do you solve it?

**Comment by chakhalyan1** [comment]
I also join the quetion

**Comment by sajukassim** [comment]
Ys. The fix i mentioned in my answer. Host is 0.0.0.0  which fix my prob

**Comment by chakhalyan1** [comment]
thanks

**Comment by schloerke** [comment]
Closing as it seems answered
