### ISSUE TITLE
Request of a -generated- list of Endpoints via the API

### ISSUE THREAD

**Issue by JFJanssen** [trestletech/plumber#26]
Hi,

This is a fantastic package. I'm using it for some dashboarding functionality, and what I'd like to offer the users is some documentation in the form of a list of Endpoint, i.e. a programmatic way to tell the users what functionality is present on the server currently running.

I can do this via a manually constructed list, which I then will have to maintain, and which may contain errors. So, how do I programmatically make a list of available Endpoints, the result of which I can serve to users?

Take care,
JFJanssen

**Comment by trestletech** [comment]
Thanks for the kind words. I agree this would be a great feature. I'm thinking that it should be possible to generate API docs from roxygen docs attached to each function. Not sure how quickly I'll be able to get to this, but I definitely like the idea.

**Comment by JFJanssen** [comment]
Any kind words for Plumber are more then well deserved.

In addition to RoxyGen, I was thinking more along the line of creating R-code within a Plumber-"unit/page/..." that can list the available functionality as an API-call. 
Functionality like "Dear R-Plumber-server, what kind of things can I ask of you?"

Does that make sense?

**Comment by trestletech** [comment]
Totally. I think it would need to integrate with the plumber annotations, but I think roxygen would be a nice fit for the "what parameters does this endpoint support?" questions.

Something like

```
#' @param count The count of units to be purchased.
#' @param item The item code to be purchased
#* @post /purchase
function(count, item){
  # ...
}
```

Then plumber could consolidate all of that into an HTML file that shows that endpoints are available and how to use them.

**Comment by JFJanssen** [comment]
Totally agree. Roxygen would create very (human) readable documentation.
Would the Roxygen documentation also be machine-readable?

**Comment by 1beb** [comment]
@trestletech That's an excellent approach because then you could technically write documentation for both purposes in one.

**Comment by trestletech** [comment]
I think this is covered with the experimental support for Swagger that's in now. See https://github.com/trestletech/plumber/blob/master/inst/examples/11-car-inventory/plumber.R#L13-L17 for an example, then you can hit `/swagger.json` for Swagger documentation about your service, and `/__swagger__/` to see an interactive UI.
