### ISSUE TITLE
swagger ui css js cdn is blocked. How can I use different CDN?

### ISSUE THREAD

**Issue by shizidushu** [trestletech/plumber#262]
Unfortunately, [swagger ui cdn in your package](https://github.com/trestletech/plumber/blob/master/inst/swagger-ui/index.html) is blocked in china.

Can you provide a way to use differnt cdn? Or just change it to a cdn that is not blocked.

**Comment by trestletech** [comment]
Closing as dup of #189. I think we have a path forward on that one, but just haven't had the bandwidth to do the work. PR's welcome!
