### ISSUE TITLE
Plumber  Issues

### ISSUE THREAD

**Issue by NanaAkwasiAbayieBoateng** [trestletech/plumber#277]
I am new to Plumber and going through the tutorial on the package page, I  have an issue with replicating what's on the website. I keep getting these errors below

`Starting server to listen on port 8000
Running the swagger UI at http://127.0.0.1:8000/__swagger__/
`

`

5. | execCallbacks(timeoutSecs)
-- | --

`

**Comment by NanaAkwasiAbayieBoateng** [comment]
`

5. | execCallbacks(timeoutSecs)
-- | --


`

**Comment by schloerke** [comment]
@NanaAkwasiAbayieBoateng What R code are you loading first to run into this error?  (This way I can reproduce it on my end)

**Comment by NanaAkwasiAbayieBoateng** [comment]
Thanks. I am able to get around the earlier issues I was having by launching plumber from rstudio.

**Comment by schloerke** [comment]
Glad it's working! I'm going to close this issue for now.  Please feel free to reopen if you run into it again.
