### ISSUE TITLE
[Help] Configuring HTTPS for plumber on AWS ("Amazon Cloud")

### ISSUE THREAD

**Issue by almeidaxan** [trestletech/plumber#284]
I've been trying to secure (i.e. HTTPS) a plumber server that has been running on my AWS EC2 instance, but I'm having a hard time attempting that.

My first try was to delve deeper into the `plumber::do_configure_https()` function defined in `plumber/R/digital-ocean.R`. I understand that it uses `nginx` and `certbot` to do (almost) all the necessary work. However, I have little experience with deployment, web-services and such (especially programming-related). So doing the reverse-engineering to replicate everything from `plumber::do_configure_https()` on AWS would be quite a work for me.

Thus, I'm wondering if anyone has already gone through a similar situation and/or might have any material that could help me with?

**Comment by almeidaxan** [comment]
I actually managed to perform the necessary adjustments on `plumber::do_configure_https()` and achieve what I needed.

I'll be closing this issue since no help is needed anymore.

If anyone needs help in the future with something similar to this issue, please feel free to contact me.

**Comment by MarcinKosinski** [comment]
@almeidaxan would you mind sharing what changes you made so it works on AWS?

**Comment by almeidaxan** [comment]
@MarcinKosinski Sure. I documented the whole process as a tutorial (see the PDF below).
It has been a while since I wrote that, so some things might be outdated.  Let me know if it helps.

[plumber-https.pdf](https://github.com/rstudio/plumber/files/4293950/plumber-https.pdf)

**Comment by MarcinKosinski** [comment]
Wow. Thanks for the prompt and kind reply @almeidaxan . I'm gonna dig into that! This looks like a good material for a blog post, that you could share on GitHub pages!
