### ISSUE TITLE
How to get username from rsconnect using plumber? 

### ISSUE THREAD

**Issue by bharath222** [trestletech/plumber#285]
Hi,

I am trying to get the username from rconnect so that I can use that username in my code for security level purposes. For example, if someone login to "https://rconnect.com/?user=bharath". I want to write a function getUser() to get that username "bharath" as getUser()$username from the headers after authenticated by the Connect Server.

Below is the code which I have written but this only filters the username and forward to the next handler. But I want to return the username.

#' Gets the username from the headers after authenticated by the Connect Server
#' @filter setuser
getUser <- function(req)
{
  credStr <- req[["HTTP_RSTUDIO_CONNECT_CREDENTIALS"]]
  creds <- list()
  if (!is.null(credStr)){
    creds <- jsonlite::fromJSON(credStr)
  }
  
  req$username <- creds$user
  
  plumber::forward()
  
}

Source of code: https://www.rplumber.io/docs/routing-and-input.html#filters

I definitely believe that there should be some easier way to solve this. Could you please help resolve this issue. Thanks.

**Comment by trestletech** [comment]
Hi. Please see http://docs.rstudio.com/connect/user/plumber.html#user-meta-data-1 for a more secure way to capture the authenticated username from your plumber app.

**Comment by bharath222** [comment]
Thank you very much for the link. I understood the functions but how do I call the second function to get the username. Let's assume the second function as getUser.

getUser <- function(req, res){
  user <- getUserMetadata(req)
  username <- user[["user"]]
  if (!is.null(username)) {
    return(username)
  } else {
    return(list(message = paste0("Howdy, stranger.")))
  }
}

I am returning only the username. Now, to get the username by calling the function, should I call it as getUser(req, res) or getUser(username, res) or getUser()? All of these are not working.

**Comment by bharath222** [comment]
Got it, thanks for your help.
