### ISSUE TITLE
Is there any way to share the data (.SQL files, .R files) between the application and the API? 

### ISSUE THREAD

**Issue by bharath222** [trestletech/plumber#286]
The application and the API are two different projects in two different folders. I would like to know if there is any way to store the data files in one place instead of moving the files every time we update the data. 

Any comments or suggestions are highly appreciated.

**Comment by schloerke** [comment]
You should be able to supply a file location when reading data or connecting to a data base.

Unfortunately, this is not a plumber issue.  So I am closing the issue.  

Please check out https://community.rstudio.com/ for a R focused community forum.
