### ISSUE TITLE
Swagger not working inside docker?

### ISSUE THREAD

**Issue by ognjenantonijevic** [trestletech/plumber#288]
Hi, I have installed plumber inside Docker and everything is fine, except swagger is not working (returns 404). Has anyone had simillar issues?

**Comment by trestletech** [comment]
See the `swagger=TRUE` parameter in the `run()` call. It defaults to only be enabled when in an interactive session for security reasons. If you'd like to opt-in in on a server, you'll need to explicitly set that param to TRUE.

**Comment by ognjenantonijevic** [comment]
Works now, thanks a lot!
