### ISSUE TITLE
How to enforce HTTPS usage with plumber

### ISSUE THREAD

**Issue by neonira** [trestletech/plumber#291]
I am currently creating many web servers using R and plumber. This seems to work fine. Nevertheless I haven't found a way to tell plumber to serve endpoints thru HTTPS instead of HTTP. Any idea to do so? 

I browsed the plumber documentation several times without any real progress on that question.

Any recipe available or some hints?

**Comment by cderv** [comment]
I think this is a duplicates of #99 where you can find some answers.
