### ISSUE TITLE
Chinese characters are not supported

### ISSUE THREAD

**Issue by shangfr** [trestletech/plumber#296]
Is there any way to set the character set so that the plumber can support Chinese characters?
谢谢！

**Comment by schloerke** [comment]
@shangfr Do you have a small example plumber file?  This way I can reproduce / fix the error you're seeing.

Thank you in advance!

**Comment by shangfr** [comment]
> @shangfr Do you have a small example plumber file? This way I can reproduce / fix the error you're seeing.
> 
> Thank you in advance!

**Comment by shrektan** [comment]
@shangfr It should be fixed via the PR #312 and #314. You can try after the two PRs being merged. 😄

**Comment by shangfr** [comment]
Thank you. I appreciate your help. Thanks.
