### ISSUE TITLE
How to return a 40* (status) from a GET?

### ISSUE THREAD

**Issue by AndreGuerra123** [trestletech/plumber#302]
```r
assert<- function(res,val,msg){
  if(!val){
    res$status <- 404
    res$msg <- msg
  }
}

#* Get list of available datasetsfor a user
#* @param userid userid
#* @get /datasets/available
function(userid){
  assert()
  MORE CODE.....
  return()
}
```

How do I get to the result (res) parameter from within a get function in plumber? I'm used to other API in flask and js which usually carry the req,res,(next) parameters at the top of the function. But here the request params are passed directly to the function.

**Comment by schloerke** [comment]
@AndreGuerra123 Check out https://www.rplumber.io/docs/programmatic-usage.html#defining-endpoints for a more programmatic approach to defining the router
