### ISSUE TITLE
no message in error handling

### ISSUE THREAD

**Issue by shizidushu** [trestletech/plumber#304]
```
#' Generate a friendly error
#' @serializer unboxedJSON
#' @get /friendly
function(res){
  if (TRUE) {
    msg <- "Your request did not include a required parameter!"
    res$status <- 400 # Bad request
    list(error=msg)
    plumber::forward()
  }
  "TEST"
}
```

It returned status 400 correctly but msg (Your request did not include a required parameter!) not displayed and it shows "TEST"

**Comment by schloerke** [comment]
To force an error to be called, you must return the error list.

```r
#' Generate a friendly error
#' @serializer unboxedJSON
#' @get /friendly
function(res){
  if (TRUE) {
    msg <- "Your request did not include a required parameter!"
    return(list(error=msg))
  }
  "TEST"
}
```

In your example, the `"TEST"` is being kept as the message as it's the last item being called even if the `if` statement is hit.  In the `plumber::forward()` examples (see [Return a Response](https://www.rplumber.io/docs/routing-and-input.html#return-a-response)), the `plumber::forward()` object is the last object called (and also returned).

Also, if an error is to be returned, the route can not also be forwarded. 

Please let me know if this solves your issue!  Closing for now.

\-Barret
