### ISSUE TITLE
JSON not boxing properly

### ISSUE THREAD

**Issue by ar0ra1** [trestletech/plumber#305]
In R, returning using
```
toJSON(data.frame(ships), auto_unbox = T)
``` 

When checking in browser it only returns one array and everything boxed into one
```
[
  "[{\"ships\":\"1945\",\"_row\":\"Second Class\"},{\"ships\":\"5968\",\"_row\":\"Standard Class\"},{\"ships\":\"1538\",\"_row\":\"First Class\"},{\"ships\":\"543\",\"_row\":\"Same Day\"}]"
]
```

**Comment by schloerke** [comment]
If at the end of your function, you're returning a JSON string, plumber will then serialize the JSON serialized data.

Try to return `data.frame(ships)` and add `#' @serializer unboxedJSON` to your plumber tags.  Ex:

```r
#' @serializer unboxedJSON
#' @get /
my_function <- function() {
  data.frame(ships)
}
```

**Comment by schloerke** [comment]
Link to serializer docs: https://www.rplumber.io/docs/rendering-and-output.html#serializers

**Comment by ar0ra1** [comment]
@schloerke 
Didn't work!

**Comment by layik** [comment]
For your "parse" bit, you can do that at your front [`JSON.parse`](https://www.w3schools.com/js/js_json_parse.asp) is made for that. What was happening to your earlier code, was that it was being double serialized hence the \" escape values.

Add whatever you like and just return the dataframe (as @schloerke said) and let `plumber` do the work. Sounds like this is not an issue but help wanted one.
