### ISSUE TITLE
When run r$run(port=8000, it is not working

### ISSUE THREAD

**Issue by francisliyy** [trestletech/plumber#306]
I use another machine to run plumber, but when it starts up, it only output "Starting server to listen on port 8000", without "Running the swagger UI at http://127.0.0.1:8000/__swagger__/", then I can access the API, what happened? Nothing print out on the console
![image](https://user-images.githubusercontent.com/6333979/45551525-38f4a980-b7fc-11e8-9649-3aa891962274.png)

**Comment by francisliyy** [comment]
thought no swagger output, it is still working

**Comment by schloerke** [comment]
swagger is set by default if the environment is interactive.  When you run your server in a non interactive shell, make sure to turn it on manually.
