### ISSUE TITLE
QueryString parser limit?

### ISSUE THREAD

**Issue by layik** [trestletech/plumber#316]
Does [this](https://github.com/trestletech/plumber/blob/master/R/query-string.R#L22) mean that when `localhost:8000/foo?bar=1&baz=2` only `bar` is grabbed?

```
server <- plumber::plumber$new()
server$handle("GET", "/foo", function(res, ...){
  print(list(...))
  res
})
server$run(port = 8000)
```
and
```curl localhost:8000/foo?bar=1&baz=2```

R console shows
```
<environment: 0x115dfb3c8>

$bar
[1] "1"
```

I will try to see if we can get the list of the query strings but I still have a [Docs](https://github.com/trestletech/apis-plumber/pull/14) PR to finish and not been able to do it.

A confirmation would do at this stage. A fix would be awesome!

**Comment by schloerke** [comment]
No. `strsplit` is expecting a vector of strings and will return the vector of split values for each input value.  Since there is only one input value (`"bar=1&baz=2"`) we want the first item of results.

```
strsplit("abcde", "")[[1]]

I can reproduce your behavior in terminal on mac.  With `&` being a terminal command, quoting the url string makes it work as expected.

`curl "localhost:8000/foo?bar=1&baz=2"`

**Comment by layik** [comment]
Thanks for the prompt reply @schloerke and apologies for the confusion. I am still new to R, should have spotted the function call.

**Comment by schloerke** [comment]
Np! Those are tricky

I appreciate someone digging in the code, asking questions, and making PRs for documentation! Thanks again!
