### ISSUE TITLE
plumber UI process chinese string

### ISSUE THREAD

**Issue by 7xiezsla** [trestletech/plumber#324]
Sorry my poor English ><
The Chinese string pain me two days long.

Then we find the source code ,referenced by 
https://github.com/trestletech/plumber/blob/master/R/query-string.R

In that query-string.R,
focus on line 14 to line 47 .
I found that plumber must call function (utils::URLdecode) to process querystring.

But we found that ,for example,
`%E8%81%B7%E5%A0%B4`    ( in Chinese `職場` )
it might output `職場`,
but we got `<e8> <e5>`

Therefore we do that,
```
trace(URLdecode,edit = T)
```
And we just do nothing and then return it as following,
```
function (URL) 
{
  URL
}
```
it means we can get the original URL like `%E8%81%B7%E5%A0%B4`

and we process the URL string by using function `httr::GET()`,

Eventually, we can solve Chinese string .

Full code reference by https://www.rplumber.io/docs/
```
# plumber.R

#' Echo the parameter that was sent in
#' @param msg The message to echo back.
#' @get /echo
#' @json
function(msg=''){
  require(dplyr)
  rawdata <- httr::POST('http://www.convertstring.com/zh_TW/EncodeDecode/UrlDecode',body = list('input'= msg,
                                                                                                'outputtype'= 'outputstring')) %>% httr::content()
  
  decodedstring <- rawdata %>% rvest::html_nodes('#output') %>% rvest::html_text()
  list(msg = paste0("The message is: '", decodedstring , "'"))
```
------------------------------------------------------------------------------------
```
# runplumber.R

trace(URLdecode,edit = T) # function(URL){URL} then save
plumber::plumb('plumber.R')$run()

```

**Comment by shrektan** [comment]
@7xiezsla Although not fully understand, I believe the issue is closely related to https://github.com/trestletech/plumber/issues/296 . You are using a Windows machine, correct?

The workaround as described in the #296 is by marking the param to UTF-8 explicitly : 

> ```r
> #' @get /echo2
> function(msg="",msgCN=""){
>  Encoding(msgCN) <- "UTF-8" # by marking it explicitly it will work as an adhoc solution
>  list(msg = paste0("The message is: ", msg, "---","中文消息是: ",msgCN))
> }
> ```

**Comment by 7xiezsla** [comment]
Thank you!!!
I solved it with your smart solution.
