### ISSUE TITLE
Document endpoint created with $handle in swagger

### ISSUE THREAD

**Issue by shapenaji** [trestletech/plumber#335]
Hello! 

### Summary

Had a need to add an extra endpoint outside of the plumber file via the handle method, which I did and it works fine. However, I also wanted to properly document this endpoint in swagger. (I don't want to add this to the plumber file because the plumber file in this case is variable. I want to make sure that this endpoint is always present)

### To Reproduce / Steps Taken

I added the endpoint as follows:

```
# Initialize Server -----------------------------------------------------
    srv <- plumb("R/plumber.R")

# Add heartbeat (health check) endpoint ----------------------
    srv$handle("GET", "/_ping", function(req, res) {
        res$body <- ""
        res$setHeader("Content-Type", "application/json;charset=utf-8")
        res$status <- 200L
        res
    })

```

But this gives me just an undocumented endpoint

I first tried to add the comments on this endpoint to the route directly:

```
srv$routes[['_ping']]$comments <- "A quick test to see if API is running, if so it will return 200"
```

but this returns an error because routes is an active binding in the plumber class.

I can bypass the active binding by not using `<-` and using `assign` instead: 

```
assign('comments',"A quick test to see if API is running, if so it will return 200",envir = srv$routes[['_ping']])
```

But this seems hacky and likely to break if/when active bindings are extended to handle direct assignment, or if the unexported comments object is refactored.

----------------------

### A Less Hacky Solution

Instead, I took a look at the `PlumberEndpoint` class and `handle` method in the `plumber` class,

I think this can be fixed by just allowing us access to more of the initialization parameters in the PlumberEndpoint in the method of the plumber class by letting the `handle` method accept  `...` for additional parameters passed to the underlying constructor.

See Below:

```
handle = function(methods, path, handler, preempt, serializer, endpoint, ...){
      epdef <- !missing(methods) || !missing(path) || !missing(handler) || !missing(serializer)
      if (!missing(endpoint) && epdef){
        stop("You must provide either the components for an endpoint (handler and serializer) OR provide the endpoint yourself. You cannot do both.")
      }

      if (epdef){
        if (missing(serializer)){
          serializer <- private$serializer
        }

        endpoint <- PlumberEndpoint$new(methods, path, handler, private$envir, serializer,...)
      }
      private$addEndpointInternal(endpoint, preempt)
},```

**Comment by schloerke** [comment]
closed in #341
