### ISSUE TITLE
setSerializer errors

### ISSUE THREAD

**Issue by shapenaji** [trestletech/plumber#339]
I ran into the following error when trying to change the default serializer:

```
 # Initialize Server -----------------------------------------------------
 srv <- plumb("R/plumber.R")
 srv$setSerializer(json_high_res)
Error in private$serializer <- serializer : 
  cannot change value of locked binding for 'serializer'
```

I was trying to change the default numerical precision of the json responses.

This seems like a bug.

In the meantime I'm using this incredibly ugly one-liner:
```
body(srv$setSerializer)[2] <- expression({unlockBinding('serializer', private); private$serializer <- serializer; lockBinding('serializer', private)})
 srv$setSerializer(json_high_res)
```

**Comment by schloerke** [comment]
I originally thought this was an R6 issue.  Talking with @wch, it is not an R6 issue.  

By setting the default value to be a function, all new R6 objects will treat the key as a _method_ and not a _value_. As a _method_, it is not allowed to be overwritten like a regular _value_ is after init.
