### ISSUE TITLE
Dynamic routes don't replace with values

### ISSUE THREAD

**Issue by byzheng** [trestletech/plumber#352]
Following the issues #347 and #348, I used following dynamic route in R script. The dynamic parameter msg is not replaced in the request, instead of `{msg}`. 

```{r}
#' @param msg:character message
#' @get /msg/<msg:chr>
function(msg = "") {
  list(msg = msg)
}
````

The actual curl request is 

```
curl -X GET "http://127.0.0.1:8291/msg/{msg}?msg=message%20" -H  "accept: application/json"
````

![image](https://user-images.githubusercontent.com/1657381/48820184-86af0480-ed9f-11e8-974a-6772a8b07492.png)

**Comment by schloerke** [comment]
@byzheng Which behavior are you expecting? You are supplying both a query parameter and a url with the name `msg`. 

Would you like for the url parameter to always win?

**Comment by byzheng** [comment]
@schloerke  In the REST API, the dynamic id should be replaced by the actual values. For example, "/msg/message", the keyword "<msg>" should be replaced with "message". I think it is related only for data type "chr" or missing. This problem has been solved in my pull request.

**Comment by schloerke** [comment]
I'm glad that it'll be solved in the PR.

I'm still curious what behavior you'd expect when supplied both a dynamic id and a query parameter with the same name.

`curl -x GET "http://127.0.0.1:1234/msg/A?msg=B"`

Should R call the route function with `msg = "A"` or `msg = "B"`.

**Comment by byzheng** [comment]
It should look this: curl -x GET "http://127.0.0.1:1234/msg/A"

**Comment by schloerke** [comment]
Perfect.  Thank you!

Many PRs (including yours) are going through QA process now to be merged to master.
