### ISSUE TITLE
Support sub-routers

### ISSUE THREAD

**Issue by trestletech** [trestletech/plumber#36]
Plumber routers should be able to stack on one another by giving a prefix. 

e.g.

```
prAcct <- plumb("accounts.R")
prSales <- plumb("sales.R")
pr$addRouter(prAcct, "/account")
pr$addRouter(prSales, "/sales")
```

**Comment by Rauno56** [comment]
+1

Or a simple way to combine different files with routes would also help with structuring the code.
e.g.
```
prAcct <- plumb("accounts.R")
prBoth <- prAcct$combine(plumb("sales.R"))
```

**Comment by nihonjinrxs** [comment]
I'm fine with #60 being closed as a dup of this one, but do you have any timeline for implementation of this enhancement?

**Comment by ankur-gupta** [comment]
+1 

All of these features would help us a lot to structure larger projects with lots of endpoints. 
I would really appreciate this feature being available sooner. Thanks.
