### ISSUE TITLE
Deploying Plumber on DigitalOcean

### ISSUE THREAD

**Issue by sergey-shchemenok** [trestletech/plumber#361]
Hello,
I tried to deploy my API on DigitalOcean and get Error in file(con, "wb") : cannot open the connection

```r
do_provision(unstable = TRUE, region = 'sgp1')
#> THIS ACTION COSTS YOU MONEY!
#> Provisioning a new server for which you will get a bill from DigitalOcean.
#> Adding .httr-oauth to .gitignore
#> Waiting for authentication in browser...
#> Press Esc/Ctrl + C to abort
#> Authentication complete.
#> Using default ssh keys: Caelestis
#> NB: This costs $0.00744 / hour until you droplet_delete() it
#> Waiting for create ..................
#> New server fingerprint: ba:91:9f:ba:88:93:f7:54:f9:2c:5d:9a:c3:ac:4d:eb:db:6d:41:06
#> 2 C:\Users\CAELES1\AppData\Local\Temp\RtmpuYaaRl\file74c014d55ca2/JmoftZKayv
#> Error in file(con, "wb") : cannot open the connection
#> In addition: Warning message:
#> In file(con, "wb") :
#> cannot open file 'C:\Users\CAELES1\AppData\Local\Temp\RtmpuYaaRl\file74c014d55ca2/JmoftZKayv': #> No such file or directory
#> 
traceback()
#> 9: file(con, "wb")
#> 8: writeBin(data, target)
#> 7: (function (data, filepath) 
#>    {
#>        target <- do.call(file.path, as.list(c(to, filepath)))
#>        if (verbose) 
#>            cat(sprintf("%10d %s\n", length(data), target))
#>        if (is.null(data)) 
#>            return(dir.create(target, recursive = TRUE, showWarnings = FALSE))
#>        writeBin(data, target)
#>    })(as.raw(c(0x30, 0x0a)), "cWMJuYpixl")
#> 6: ssh::scp_download(session = session, files = remote, to = local, 
#>        verbose = TRUE)
#> 5: cat(ssh::scp_download(session = session, files = remote, to = local, 
#>        verbose = TRUE), sep = "\n")
#> 4: do_scp(droplet, local, remote, user, scp = "download", keyfile, 
#>        ssh_passwd, verbose = verbose)
#> 3: analogsea::droplet_download(droplet, paste0("/tmp/", randName), 
#>        tf)
#> 2: droplet_capture(droplet, "swapon | grep \"/swapfile\" | wc -l")
#> 1: plumber::do_provision(region = "sgp1")
```

**Comment by sckott** [comment]
@trestletech I attempted to fix this problem on this branch https://github.com/trestletech/plumber/compare/master...sckott:scp-fix 

I had to fix a problem in `analogsea`, so have plumber using dev `analogsea`

I am stuck now on the `install_nginx()` call within `do_provision()` - not sure what's going on with nginx (i use caddy, so not familiar enough to help)


```r
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
Error: ssh failed
systemctl reload nginx
```

**Comment by trestletech** [comment]
Hm... I'm not sure off the top of my head. @schloerke , are you setup to test any of the DigitalOcean stuff?

**Comment by trestletech** [comment]
@sckott we were able to track this down and it looks like the change is actually a breaking change in analogsea -- I'm not sure whether or not it was intentional.

We used to be able to do something like `droplet_upload(droplet, local="myfile.txt", remote="/tmp/anothername")` and it would create a _file_ named `anothername`. This behavior changed and now analogsea will create a _directory_ named `anothername` and place a file named `myfile.txt` inside of it.

Was that an intentional change? We're trying to determine whether we should add plumber code to work around that or if it's something that might be rolled back before being widely shared.

**Comment by sckott** [comment]
Thanks for figuring it out, and sorry about that. I'll have a looko

**Comment by Btibert3** [comment]
I am not sure if this is related, but when I attempt to spin up a new droplet on DO with `do_provision`, the messages tell me that the server is starting to listen on port 8000, but when I go to the server's IP address as designated by DO on port 8000, the connection times out.

**Comment by sckott** [comment]
@Btibert3 not sure either, but thanks for chiming in here, will see if its a related issue

**Comment by schloerke** [comment]
@sckott Checking in to see if there's any update.  (Thank you for the help!)

**Comment by sckott** [comment]
was just returning to analogsea work, finished incorporating spaces (DO's S3) stuff, so now can concentrate on this. will report back soon

**Comment by schloerke** [comment]
@sckott Friendly ping.  Thank you again for the help!

**Comment by sckott** [comment]
@schloerke can you try again to confirm the problem persists. install latest `analogsea` from github `remotes::install_github("sckott/analogsea")`, then 

```r
library(analogsea)
d <- droplet_create() %>% droplet_wait()
tmp <- tempfile(fileext = ".txt")
cat("hello world\n", file = tmp)
readLines(tmp)
droplet_upload(d, tmp, "/tmp")
droplet_ssh(d, "ls /tmp")
unlink(tmp)
file.exists(tmp)
droplet_download(d, file.path("/tmp", basename(tmp)), tempdir())
file.exists(tmp)
readLines(tmp)
```

**Comment by sckott** [comment]
`droplet_upload` doesn't do what Jeff [reports above](https://github.com/trestletech/plumber/issues/361#issuecomment-450683216) for me, but maybe its just me

**Comment by sckott** [comment]
hmm, well, with my branch `scp-fix` trying `do_provision()` starts to work at first, then fails after instaslling all R pkgs with 

```r
Error in FUN(X[[i]], ...) :
  File or directory does not exist: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/plumber/examples/10-welcome/**
```

no matter what I do with tweaking the scp_upload call, i can't get that part to work. any thoughts?

**Comment by trestletech** [comment]
Went to revisit this today and we were bit by an unrelated bug. The CRAN Ubuntu mirror is having some signing issue so we can't install R on these droplets we're trying to provision. 🤦‍♂️

```
E: The repository 'https://cran.r-project.org/bin/linux/ubuntu xenial/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```
 Error: ssh failed
sudo apt-get install -y --force-yes r-base r-base-dev 
```

We're going to try again next week after this is -- hopefully -- fixed.

**Comment by sckott** [comment]
Okay, just submitted a new version to cran, but they rolled it back saying ssh pkg can only be in Suggests or removed from the pkg - so thats fun - guess it's going in Suggests

**Comment by sckott** [comment]
now on cran, as you probably saw

**Comment by schloerke** [comment]
Fixed in Master
