### ISSUE TITLE
Why doesn't allow swagger running on 0.0.0.0

### ISSUE THREAD

**Issue by shrektan** [trestletech/plumber#375]
https://github.com/trestletech/plumber/blob/5fcf2dc62ee462522f2f4f60421d565b18d6841a/R/plumber.R#L220-L222

Hi, I don't understand why host 0.0.0.0 has to be masked by 127.0.0.1 if swagger gets enabled?

This leads to the case that __swagger is not available in docker__.

For example, if I run this:

`docker run --rm -v "/Users/Flynn/Downloads/shinyproxy-experiements/plumber:/plumber" -p 8000:8000 rdocker R -e "plumber::plumb('/plumber/api1.R')\$run(host = '0.0.0.0', port = 8000, swagger = TRUE)"`

Not only http://127.0.0.1:8000/__swagger__/ returns error but also the normal APIs like http://127.0.0.1:8000/plot ... The cause is that the host 0.0.0.0 gets masked by 127.0.0.1 thus will not be exposed to the docker's host machine.

So I have to remove the trailing `swagger = TRUE` in the above code.

**Comment by schloerke** [comment]
@trestletech Should this host location only be updated for swagger internally?

**Comment by trestletech** [comment]
Yeah, I think this is a bug. I'm having a hard time getting my head all the way around it, but I believe that the goal here was to say: "if you give me a real IP, then I should use that as my advertised Plumber API host." But if you just give me 0.0.0.0, then I don't know what you're real IP is, so the best guess I can make is to point you to localhost.

But it sounds like there's a bug in this logic. In the event that you tell plumber to use 0.0.0.0, I'm still not sure what IP I should point your Swagger docs at. But...

**Comment by schloerke** [comment]
I'm guessing we could try and do it with swagger at `127.0.0.1`, but keep the actual plumber app at `0.0.0.0`

**Comment by schloerke** [comment]
Switching logic to only change the route (from `0.0.0.0` to `127.0.0.1`) for the `swaggerCallback` if being called within RStudio IDE (as the IDE doesn't like `0.0.0.0` hosts). Users will not be notified of this host change.

The swagger message's host will use the result of `getOption('plumber.apiHost', host)`.
