### ISSUE TITLE
Question: interacting with the R process running plumber

### ISSUE THREAD

**Issue by neuwirthe** [trestletech/plumber#377]
Is it possible to have plumber running, listening, and executing and
at the same time working with the data in the namespace of this process from another interface?
Situation: the plumber process stores data in a global variable and I want to access these date from a command line window while the plumber process is still listening.
When developing applications, one can check if R really got the data it expected.

**Comment by schloerke** [comment]
Short answer to inspecting another R process, no. Instead, use `browser()` in your plumber code and inspect in the plumber R process.

-------------------

With R's "pass by value" setup, it is not easy to share variables between processes on the machine.  This can be done, with the easiest way of accomplishing it over two completely independent processes is with a database.  

------------------------

That being said, if you run your plumber api within a regular R sessions (not Rscript), you can insert `browser()` statements into your code and debug your code within the plumber process.  When ever the `browser()` line of code is reached within your API, R will give you control to inspect your function.  I use this all the time when developing plumber.

`browser()` description: https://adv-r.hadley.nz/debugging.html#browser . I use `c` (continue), `n` (next line), and `Q` (quit browser) all the time.  You are also allowed to have multiple `browser` statements in your code.

**Comment by shrektan** [comment]
If the data is not that large, you may implement a [filter](https://www.rplumber.io/docs/routing-and-input.html#filters) to save the global data to a rds file on disk. Then you can read that rds file in another R process...

**Comment by schloerke** [comment]
Closing as Issue as it seems answered. Please open a new issue and reference this one if you have unanswered questions.
