### ISSUE TITLE
Unable to connect to plumber under Windows

### ISSUE THREAD

**Issue by dlindelof** [trestletech/plumber#379]
I run the following code from RStudio under Windows:

``` r
  api <- plumber::plumber$new()
  api$handle("GET", "/", function() { print("Hello world")})
  api$run(port = 8080)
  # Starting server to listen on port 8080
  # Running the swagger UI at http://127.0.0.1:8080/__swagger__/
```

But when I visit `http://localhost:8080` from Chrome I get a message saying the connection attempt timed out:

![image](https://user-images.githubusercontent.com/245328/52118125-d0c12b80-2615-11e9-8aa6-9f23309c75b2.png)

Using `plumber` version `0.4.6`.

**Comment by shrektan** [comment]
I just tried using your same code. It works perfectly on my computer.

**Comment by dlindelof** [comment]
Restarting my computer did the trick. Go figure.

**Comment by shrektan** [comment]
Please close the issue if no further problems. Thanks.
