### ISSUE TITLE
change URL for __swagger__

### ISSUE THREAD

**Issue by dotRData** [trestletech/plumber#394]
how change we change the URL for swagger UI ?

```
whoami <- system("whoami", intern = TRUE)
plumber::plumb(glue::glue("/home/{whoami}/data-science/plumber/plumber.R"))$run(port=7867, 
                                                                                host="0.0.0.0",
                                                                                swagger=TRUE)

Running plumber API at http://0.0.0.0:7867
Loading required namespace: swagger
Running Swagger UI  at http://127.0.0.1:7867/__swagger__/
```

**Comment by dotRData** [comment]
if run from rstudio-server .. i get this error as well
```r
<simpleError: 'swagger_spec' is not an exported object from 'namespace:swagger'>
```

**Comment by schloerke** [comment]
Currently, there is no option for changing the swagger route.  Why do you want to change it? (What do you want to change it to?)

If you'd like to handle it manually, set `swagger = FALSE` in the `run` call.  Add a route where you'd like it to be served.  If you save the result from `plumb` (ex: `pr <- plumb("someFile.R")`),  you can get the swagger information with `pr$swaggerFile()` and serve it in a custom route.

---------------------------------

`swagger::spec` in the GitHub branch of `swagger`.  Until it get's onto CRAN, you might have to install with `remotes::install_github("rstudio/swagger")` or `remotes::install_github("trestletech/plumber", dependencies = TRUE)`.

**Comment by dotRData** [comment]
I am running plumber on a server, and i am not able to connect to 127.0.0.1:7867/__swagger__/, from outside the localhost, I need to make that UI publicly accessible.

may be installing ``remotes::install_github("rstudio/swagger"`` will solve the issue. will look into it tomorrow.

**Comment by dotRData** [comment]
started working after installing the dev version of swagger ``remotes::install_github("rstudio/swagger")``

Thanks :)

**Comment by jakesauter** [comment]
Following up on this thread, any easier way to set this option now? Use case: docker container on AWS ECS

**Comment by aaronbrezel** [comment]
In a similar situation. 

I was able to get close by following the directions above and adding:

```
#' @tag documentation
#' @get /v1/__docs__/
function() {
  return(pr$swaggerFile());
}
```
to my plumber.R file. But this only returns a JSON represention on the documentation. I'm really looking for the full swagger UI.
