### ISSUE TITLE
Programmatic Usage with Dynamic Routing

### ISSUE THREAD

**Issue by mmuurr** [trestletech/plumber#400]
Do you have any examples of Programmatic Usage (i.e. explicitly constructing the handlers with the `$handle` method) with dynamic routing (e.g. `/user/<from>/connect/<to>`)? I can't find any documentation on how to marry these two concepts.

Thanks a ton for all your work, too, BTW, it's great!

**Comment by schloerke** [comment]
Check this out: https://www.rplumber.io/docs/programmatic-usage.html

Glad you enjoy the pkg!

**Comment by mmuurr** [comment]
I guess I meant _specifically_ how to handle setting up endpoints with dynamic elements in their paths. Should the same `<varname>` templating be used for the programmatic cases, or is there a more general 'wildcard' pattern? I can probably figure this out from the source itself, but figured it'd be useful to have the dynamic endpoint case as one of the programmatic examples.

Ciao!

**Comment by schloerke** [comment]
Ah, correct.  The same `/page/<varname>/<othervarname>` url routes should be used.  Be sure to add the variable names to your resolving function.  

```r
pr$handle("GET", "/page/<varname>/<othervarname>", function(req, res, varname, othervarname) {
  # ...
})
```

I don't know of a wild card setup for routes.  It seems like a fair feature to have.

**Comment by mmuurr** [comment]
Got it, thanks much!
I'll be working out a particular use case of this over the next day or so ... if you'd like any contributions to the rblumber.io docs, just let me know and I'll be happy to submit a PR (is that site in a separate GitHub repo?).

Cheers!

**Comment by schloerke** [comment]
@mmuurr Documentation updates are always welcome! 

The docs website is created from this repo: https://github.com/trestletech/apis-plumber
