### ISSUE TITLE
Symbol links in latest docker image are broken

### ISSUE THREAD

**Issue by iabramov** [trestletech/plumber#402]
/usr/lib/R/ is missed!

ls -la  /usr/local/bin/
drwxr-xr-x 1 root root 4096 Mar 16 20:23 .
drwxr-xr-x 1 root root 4096 Feb 28 00:00 ..
lrwxrwxrwx 1 root root   51 Mar 16 20:23 install2.r -> /usr/lib/R/site-library/littler/examples/install2.r
lrwxrwxrwx 1 root root   56 Mar 16 20:23 installGithub.r -> /usr/lib/R/site-library/littler/examples/installGithub.r
lrwxrwxrwx 1 root root   50 Mar 16 20:23 install.r -> /usr/lib/R/site-library/littler/examples/install.r
lrwxrwxrwx 1 root root   56 Mar 16 20:23 testInstalled.r -> /usr/lib/R/site-library/littler/examples/testInstalled.r

Also r is missed or not in path

**Comment by schloerke** [comment]
🎊
