### ISSUE TITLE
Pass arguments to `jsonlite::toJSON` serializer

### ISSUE THREAD

**Issue by brianwdavis** [trestletech/plumber#403]
https://stackoverflow.com/questions/55287408/r-post-response-using-plumber-api-converts-10-decimal-places-double-desired-pre/

This issue came up on StackOverflow, where the default in `toJSON(..., digits=4)` was not acceptable. The workaround was to pre-serialize the result manually.

This is related to issue https://github.com/trestletech/plumber/issues/220 I believe.

Reprex:

```
library(plumber)

#* @apiTitle A Test API

#* Run a simple function
#* @get /

function(req, res) {
  x <- rnorm(1)
  res$body <- jsonlite::toJSON(x, digits = NA)
  res
}


# plumb("plumber_1.R")$run(port = 5762)
# Save this file as e.g. "plumber_1.R" and run the commented line
```

Then you should be able to get a response like this:

```
library(httr)
y <- GET("http://127.0.0.1:5762/")
content(y, as = "text")
```

> `[1] "[-0.982448323838634]"`

The ideal solution would be passing arbitrary arguments following a tag in the plumber definition, such as:

`#' @serializer JSON digits 12`

**Comment by schloerke** [comment]
This is fixed in #356 and is on master branch.

You'll need the line:

```
#' @serializer json list(digits = 12)
```

or for `json` specificially

```
#' @json(digits = 12)
```
