### ISSUE TITLE
swagger UI attributes

### ISSUE THREAD

**Issue by Tixierae** [trestletech/plumber#405]
I have two questions related to the swagger UI. Right now, I'm using:

```r
#* @tag my_endpoint
#* @param my_param:numeric description
#* @response 200 successful operation
#* @response 400 bad request
#* @get /my_endpoint
function(my_param,res){
	...
}
```
* However, despite defining my responses using `@response`, `default | Default response` still shows in the responses section of swagger UI. How can I remove it? 

* Also, for each endpoint, I'd like to add in the documentation an example of a full request, e.g., `https://myapi.com/my_endpoint?my_param=foo`. Right now, I'm adding the example using `@apiTag my_endpoint` but it's not optimal. How to use the [dedicated example keyword](https://swagger.io/docs/specification/adding-examples/) of swagger so that I can have a dedicated example field?

Thank you very much in advance for your help!

**Comment by EDiLD** [comment]
You can use your own `swagger.yml` to make use of the full openapispec:

```r
library("plumber")
plumb("api.R")$run(
  host = host,
  port = port, 
  swagger = function(pr, spec, ...) {
    spec <- yaml::read_yaml("swagger.yml", handlers = list(seq = function(x) x))
    spec
  })
```

While you get all functionality of OAS3, you loose the inline decorators...

**Comment by Tixierae** [comment]
Thank you for this potential solution. Closing the issue for now.
