### ISSUE TITLE
Is it possible to use SSL with an API endpoint?

### ISSUE THREAD

**Issue by dzackgarza** [trestletech/plumber#41]
Just wondering, as I'm trying to come up with a (relatively) secure authentication scheme.

**Comment by trestletech** [comment]
The underlying HTTP library we use (httpuv, libuv) doesn't really do much with TLS/SSL as far as I can tell. So plumber wouldn't be able to do HTTPS natively.

The work-around would be to setup nginx/Apache/ELB/etc. as a reverse proxy in front of plumber and do the SSL termination there. If you Google "SSL termination nginx" (or whatever proxy you want to use), you should get some good instructions on how to accomplish this.

'Hope that helps!
