### ISSUE TITLE
Capturing output and messages

### ISSUE THREAD

**Issue by katiamar63** [trestletech/plumber#414]
Hi,
I would like to write a Plumber script which could execute any given script sent in parameter and capture output and messages. So far, the best results I got with the following code
```
#' @post /executescript
function(txtScript,data){
resultVariable<- capture.output(eval(parse(text=txtScript)),file = NULL, append = TRUE,
type = c("output", "message"), split = TRUE)
}
``` 
but this is not enough for me, since I would like to capture all the output from all function calls in the script. In the code above, only output for last  call is saved in `resultVariable`.

I also tried with 
```
tc <- textConnection("resultVariable","w")
sink(tc, append = FALSE, type = c("output", "message"))
eval(parse(text=txtScript))
sink(NULL, type = c("output", "message"))
close(tc)
result<-print(resultVariable)
```
but then I had either empty `result` or 'cannot change value of locked binding for resultVariable' when I tried to copy textConnection before closing. I also tried 'evals' but it didn't work with functions.

How can I evaluate script and send response with captured output with Plumber ?
Thanks in advance for any help

**Comment by schloerke** [comment]
Check out the `evaluate` package.  Specifically `evaluate:: evaluate(txtScript)`.  This will work with graphics as well.

```r
❯❯ evaluate:: evaluate("mean(1:10)\nsd(1:10)\n4")
[[1]]
$src
[1] "mean(1:10)\n"

attr(,"class")
[1] "source"

[[2]]
[1] "[1] 5.5\n"

[[3]]
$src
[1] "sd(1:10)\n"

attr(,"class")
[1] "source"

[[4]]
[1] "[1] 3.02765\n"

[[5]]
$src
[1] "4"

attr(,"class")
[1] "source"

[[6]]
[1] "[1] 4\n"
```


--------------------

Please be careful of users submitting malicious code.  See https://github.com/jeroen/RAppArmor#readme for a nice way to help curb their efforts.

**Comment by katiamar63** [comment]
Thank You Very Much!!! This is it!!!
Earlier I installed wrong evaluate function (wrong package), but the version of  Yihui Xie is what I was looking for.
