### ISSUE TITLE
Deploy manipulateWidget using R Plumber

### ISSUE THREAD

**Issue by maheshKulkarniX** [trestletech/plumber#415]
When I Host manipulateWidget using R Plumber it gives the following Error.

Error:

```{r}
<simpleError in get(fun, mode = "function", envir = parent.frame()): object 'shiny' of mode 'function' was not found>
<simpleError in system.file(config, package = package): 'package' must be of length 1>
```

code:- 
File Name:- html_widget.R
```{r}
#' @get /plotly
#' @serializer htmlwidget
library(plotly)
data(iris)
library(plumber)
library(manipulateWidget)
varNames <- names(iris)[1:4]

plotlygraph <- function(){manipulateWidget(
  plotClusters(xvar, yvar, nclusters),
  xvar = mwSelect(varNames),
  yvar = mwSelect(varNames, value = "Sepal.Width"),
  nclusters = mwSlider(1, 10, value = 3),
  plot_ly(x = ~iris[[xvar]], y = ~iris[[yvar]], color = ~clusters,
          type = "scatter", mode = "markers") %>% 
    layout(xaxis = list(title=xvar), yaxis = list(title=yvar))
)
}
```

```{r}
r <- plumber::plumb("html_widget.R")
r$run(host="0.0.0.0", port=8000)
```
                                                                  
                                                               regards,
                                                               Mahesh Kulkarni

**Comment by schloerke** [comment]
I could not get the regular`manipulateWidget()` code to work.  With a different example (using dygraphs), I achieved a similar error about missing the dygraphs function.

It is **very** important where the plumber tags are placed.  They should be directly above the route function.  Currently, plumber is trying to say that `library(plotly)` is an htmlwidget route.  I don't know how it found the `plotlygraph` function and was able to work.

Nice job on the htmlwidget serializer, that was my first guess.

Changed the example to use `manipulateWidget`'s vignette example:

```r
library(plotly)
data(iris)
library(plumber)
library(manipulateWidget)
library(dygraphs)
varNames <- names(iris)[1:4]

#' @get /plotly
#' @serializer htmlwidget
plotlygraph <- function() {
  mydata <- data.frame(
    timeId = 1:100,
    series1 = rnorm(100),
    series2 = rnorm(100),
    series3 = rnorm(100)
  )
  manipulateWidget(
    dygraph(mydata[range[1]:range[2], c("timeId", series)], main = title),
    range = mwSlider(1, 100, c(1, 100)),
    series = mwSelect(c("series1", "series2", "series3")),
    title = mwText(),
    .compare = list(
      title = list("First chart", "Second chart"),
      series = NULL
    )
  )
}
```

**Comment by maheshKulkarniX** [comment]
Thanks, @schloerke  for the reply.
But in our organization, we use the plotly package.
So if you add plotly support then it will be a big help for us.
I'll also try to work on it.
Actually, we use research on how to connect R and Databricks and
How to send Plots from R Plotly to Databricks UI.
And Databricks is not supported to R Shiny that's why we are looking to use 
manipulateWidget() package through plumber.
If you know about databricks and R then You can also suggest any way 
to resolve this issue.

**Comment by schloerke** [comment]
Plotly is an `htmlwidget`, so you should be able to return plotly plots as well with the `#' @serializer htmlwidget`.

**Comment by schloerke** [comment]
Closing as original question has been answered.  

Please visit https://community.rstudio.com/ for general R language questions / support.
