### ISSUE TITLE
return uri to redirect to

### ISSUE THREAD

**Issue by yonicd** [trestletech/plumber#418]
how do i build a return from a get so based on the input a new url is created and as a result a redirect to the uri is invoked? i can return the uri as a string via `@html`.

**Comment by schloerke** [comment]
If you visit `127.0.0.1:12345/` it will redirect to `127.0.0.1:12345/redirected` with the value "worked!".   Please see https://en.wikipedia.org/wiki/URL_redirection#HTTP_status_codes_3xx to get the correct status code (permanent vs temp).  


```r
# plumber.R
#' @get /redirected
function(req, res) {
  "worked!"
}

#' @get /
#' @html
function(req, res) {
  res$status <- 303 # redirect
  res$setHeader("Location", "./redirected")
"<html>
  <head>
    <meta http-equiv=\"Refresh\" content=\"0; url=./redirected\" />
  </head>
  <body>
    <p>Please follow <a href=\"http://www.example.com/\">this link</a>.</p>
  </body>
</html>"
}
```

Server
```r
plumber::plumb("plumber.R")$run(port = 12345)
```

Testing
```bash
# bash

curl http://127.0.0.1:12345/
# <html>
#   <head>
#     <meta http-equiv="Refresh" content="0; url=./redirected" />
#   </head>
#   <body>
#     <p>Please follow <a href="http://www.example.com/">this link</a>.</p>
#   </body>
# </html>

# Follow redirects using curl
curl http://127.0.0.1:12345/ -L
# ["worked!"]
```

**Comment by yonicd** [comment]
Thanks! I’ll try this out.

**Comment by yonicd** [comment]
how would it work in this case that I want to redirect to a site outside of my server?

```#' @get /docs
#' @html
function(req, res) {
  res$status <- 303 # redirect
  res$setHeader("Location", "https://github.com")
  "<html>
  <head>
    <meta http-equiv=\"Refresh\" content=\"0; url=https://github.com\" />
  </head>
  <body>
    <p>Please follow <a href=\"http://www.example.com/\">this link</a>.</p>
  </body>
</html>"
}```

**Comment by schloerke** [comment]
Yup. That should work!  

The header is for applications like curl.  The `meta` tag within the html `head` is for browsers.  (I forgot to change `example.com` as well.)

**Comment by yonicd** [comment]
looks like something isn't quite right still.

![Screen Shot 2019-04-30 at 9 27 40 AM](https://user-images.githubusercontent.com/1755487/56965001-3bf19f80-6b2a-11e9-9e49-3feba7592569.png)

**Comment by yonicd** [comment]
ah the swagger returns an error, but the app redirects correctly.

**Comment by schloerke** [comment]
Ah.  The response type is set to `application/json`.  It needs to be `application/html`.

**Comment by schloerke** [comment]
Closing for now.  I'll make an issue for getting content type / swagger info from serializers
