### ISSUE TITLE
How to live stream plot using Plumber

### ISSUE THREAD

**Issue by maheshKulkarniX** [trestletech/plumber#419]

**Comment by schloerke** [comment]
Plumber does not currently support web sockets / streaming.  I suggest making a route that can handle "return data since time t" with `t` being a parameter.

**Comment by maheshKulkarniX** [comment]
@schloerke  thanks for reply

**Comment by schloerke** [comment]
@maheshKulkarniX  Check out https://github.com/rstudio/websocket for websocket support within R.  It's been submitted to cran (~7 days ago), just waiting for approval.
