### ISSUE TITLE
Adding PDF support

### ISSUE THREAD

**Issue by emmanuelchevallier** [trestletech/plumber#42]
Hi,

I try to send a pdf with my API in R and Plumber (Plumber is a very good idea :).

#*pdf doesn't work.

I have to modify jsonSerializer in that way to have it working : 

jsonSerializer` <- function(val, req, res, errorHandler){
  tryCatch({
    
    res$setHeader("Content-Type", "application/pdf")
    res$body <- val

    return(res$toResponse())
  }, error=function(e){
    errorHandler(req, res, e)
  })
}

.globals$serializers[["json"]] <- `jsonSerializer

Do you have another (cleaner ;) way to do that ?
Thanks

**Comment by trestletech** [comment]
Hey, sorry for the late response. I don't have a cleaner way to handle that, unfortunately. But I think that's a good feature request. There should probably be an annotation that allows you to control the outbound content-type. I'll leave this open as a marker for that.

**Comment by emmanuelchevallier** [comment]
Hi,
Thanks you to accept this feature request :) !
I think it will help a lot of people because R is often used to do reporting.
Have a good day :)

**Comment by trestletech** [comment]
Ok, I have a pull request open with support for this. Do you mind helping me test it, @emmanuelchevallier ? There ended up being a decent amount of code changes to get this feature in so I want to let it soak for a few days before I bring it in.

You can get the patched version via:

```
 devtools::install_github("trestletech/plumber", ref="serializerFactory")
```

See https://github.com/trestletech/plumber/blob/serializerFactory/inst/examples/09-content-type/content-type.R for an example of how to use the new feature.

**Comment by emmanuelchevallier** [comment]
I'm here to test and help if I can :) I test it ASAP and give you feedback !

**Comment by lumadelaplace** [comment]
Hi @trestletech, I have been testing the version you mentioned above and it works perfectly with the pdf reports @emmanuelchevallier and I are generating.
Thanks a lot for adding this new feature !

**Comment by emmanuelchevallier** [comment]
Yes thanks a lot Jeff!
Next step we'll test to do an API that return graph build with Rcharts.
Plumber is the bridge between R and the rest of the IT world ! ;-)
We'll give you feedback soon !
Have a good day,
Emmanuel

**Comment by trestletech** [comment]
Great! I'm glad you're finding the package useful. Thanks for helping to validate the fix.

I just merged the PR, so feel free to hop back on the `master` branch at your leisure.
