### ISSUE TITLE
is it possible to reduce the prediction run time?

### ISSUE THREAD

**Issue by apremgeorge** [trestletech/plumber#434]
To increase performance,
For reading the model from file and running prediction function it takes 3sec, 
Instead of reading the model everytime from file, is it possible to store globally and read in the predict function
function(res){
  output <- predict(readRDS("C:/rf_wrapper.rds"), newdata = as.data.frame(readRDS("C:/Test.Rds")))
 res$body <- output
  res
}
library(plumber)
pr <- plumb("C:/plumb_test.R")
pr$run(port=8000)

**Comment by apremgeorge** [comment]
Assigning Outside reducing my time from 2300ms to 85ms
library(plumber)
library(mlr)
library(jsonlite)
model <- readRDS("C:/rf_wrapper.rds")
newdata <- as.data.frame(readRDS("C:/Test_data.Rds"))
#* @apiTitle Plumber Example API

#* @get /run
function(res){
  output <- predict(model, newdata = newdata)
  json_output <- toJSON(setNames(as.data.frame(output),c("Actual","Prob.Good","Prob.Bad","Prediction")))
  res$body <- json_output
  res
}

**Comment by apremgeorge** [comment]
Thanks

**Comment by schloerke** [comment]
I'd even move 
```r
output <- predict(model, newdata = newdata)
json_output <- toJSON(setNames(as.data.frame(output),c("Actual","Prob.Good","Prob.Bad","Prediction")))
``` 
outside of `/run` route.  Both lines do not change with the route, so they might as well be pre-computed.

```r
output <- predict(model, newdata = newdata)
json_output <- toJSON(setNames(as.data.frame(output),c("Actual","Prob.Good","Prob.Bad","Prediction")))

#* @get /run
function(res){
res$body <- json_output
res
}
```

**Comment by apremgeorge** [comment]
Thanks and Much appreciated for the reply, that reduced run time to 6ms.
