### ISSUE TITLE
JSON message body is malformed on Windows

### ISSUE THREAD

**Issue by Tixierae** [trestletech/plumber#436]
My `plumber.R` file:
```r
#* @post /test
function(req,res,param){
    print(req$postBody)
    if(!jsonlite::validate(req$postBody)){
        res$status <- 415
        return(list(errors="message body is not JSON, or not properly formatted JSON!"))
    }
}
```
Once the API is live (`library(plumber);r <- plumb("plumber.R");r$run(port=8000)`), executing `curl --data '{"param":123}'` returns the error message. However, in a R console, `validate('{"param":123}')` evaluates to TRUE.

The `print()` statement returns `"'{param:123}'"` (notice how the `""` have been removed from around `param`), which explains why the error is raised, as `req$postBody` is not proper JSON anymore. **How to access the raw, original quoted JSON with req$postBody?**

Any help would be much appreciated, thank you!

**Comment by schloerke** [comment]
... I can not reproduce this error.

```
> library(plumber);r <- plumb("plumber.R");r$run(port=8000)
Starting server to listen on port 8000
Running the swagger UI at http://127.0.0.1:8000/__swagger__/
[1] "{\"param\":123}"
```

```
~: curl 127.0.0.1:8000/test --data '{"param":123}'
{}
```

---------------

Where are you executing this?  (Me: {Mac, CRAN plumber, terminal})

**Comment by schloerke** [comment]
@Tixierae Can you please include your `sessioninfo::session_info()`? Thank you

**Comment by Tixierae** [comment]
Sorry for the late reply. Indeed, this is a platform-dependent issue. I get the error on Windows (see session info below), but I just tried and it works fine on Ubuntu.

Session info for which I see the error:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252
```
Since this is for a flask app that I'll deploy on a unix machine, everything is fine. It's just that I'll have to use Ubuntu to test the app locally.

**Comment by schloerke** [comment]
Corner cases like these make Windows development very difficult.  With the ability to run Docker on Windows (which then makes deployment easier), having plumber _mostly_ work on Windows is a bonus. 

Closing for now.
