### ISSUE TITLE
plumber api not working  as background job in  linux server cent OS 6 

### ISSUE THREAD

**Issue by GRMK11** [trestletech/plumber#456]
I created plumber api and made it work as  background job in linux server using nohup.It works fine initially but after some time it not working .every time I need to create background job again  .So please help on this issue
Regards,
Manohar

**Comment by schloerke** [comment]
This is going to be very difficult to debug without a crash log or to know why it is stoping.  

------------

For general plumber questions, open a new post in the shiny `category` with a `plumber` tag:

https://community.rstudio.com/new-topic?title=&category_id=8&tags=plumber&body=%0A%0A%0A%20%20--------%0A%20%20%0A%20%20%3Csup%3EReferred%20here%20by%20%60plumber%60%27s%20GitHub%3C/sup%3E%0A&u=barret

**Comment by schloerke** [comment]
Closing issue until reopened with more information.
