### ISSUE TITLE
Cannot select encoding of  text

### ISSUE THREAD

**Issue by jaesm14774** [trestletech/plumber#466]
Problem: Return output  is not correct in Chinese word because of encoding

Can not select encoding of text, so I don't know how to fix it.

If anyone can help me, I'm glad for it.

Programming code
![image](https://user-images.githubusercontent.com/33981395/62259432-e8e8fa80-b440-11e9-8d9f-d001dc76a19f.png)

In R studio (windows)
![image](https://user-images.githubusercontent.com/33981395/62259458-00c07e80-b441-11e9-8939-c61175659335.png)

Call by url
![image](https://user-images.githubusercontent.com/33981395/62259637-9a882b80-b441-11e9-83b5-430620265ccf.png)

**Comment by schloerke** [comment]
Does this error go away with the github version of plumber?

```
devtools::install_github("trestletech/plumber")
```

**Comment by jaesm14774** [comment]
Yes,I am not update plumber by github.

It's solved the problem.

Excellent!!  Thank you very much.

**Comment by schloerke** [comment]
Great! Thank you!
