### ISSUE TITLE
Return CSV

### ISSUE THREAD

**Issue by mattjvincent** [trestletech/plumber#54]
What is the best way to return CSV?

The JSON is great, but I'm running into issues where the bandwidth is an issue.  Thoughts?

Thanks!

**Comment by trestletech** [comment]
See https://github.com/trestletech/plumber/blob/master/inst/examples/09-content-type/content-type.R for examples here.

You can just annotate the endpoint with a special content type and then return the CSV text directly.

**Comment by mattjvincent** [comment]
Awesome!  Thank you!

Non plumber related: As I am new to R, what would be the best way to do this?

currently I am doing:

`return (data.table(id=samples$new_ids, position=all_data$coordinate, description=all_data$description, score=all_data$score))`

And I get a nice JSON object.  Would I have to dump the table to some sort of character variable and return that or is there a way to stream?  Sorry for the newb questions.

**Comment by trestletech** [comment]
You could write it out to a file and then use `readLines` to pull it back in. But there's a better way to do it by just keeping everything in memory but I don't recall the exact commands. Perhaps starting with `textConnection` would be a good start?

**Comment by mattjvincent** [comment]
Ok.  I'll look.  Thank you.
