### ISSUE TITLE
json example in README isn't working

### ISSUE THREAD

**Issue by FrankPortman** [trestletech/plumber#57]
```
Starting server to listen on port 8000

<simpleError in (function (a, b) {    as.numeric(a) + as.numeric(b)})(): argument "a" is missing, with no default>

Warning in li["message"] <- err :
  number of items to replace is not a multiple of replacement length
```

I believe the CRAN version is outdated.

**Comment by FvD** [comment]
Yes, the CRAN version is currently outdated. For the JSON example to work you need to install the development version from source or with devtools:

    devtools::install_github("trestletech/plumber")

**Comment by FrankPortman** [comment]
@FvD is there any plan to push this version to CRAN? There seem to be some decently big updates since the last version.

**Comment by FvD** [comment]
@FrankPortman we just have to wait a little bit longer for Jeff to find time to do so. Until then, an `install_github` is easiest way to go. Note that there are [breaking changes](https://github.com/trestletech/plumber/blob/master/NEWS.md) between the current version on CRAN and this development branch.

**Comment by trestletech** [comment]
Closing this issue in favor of #58. @FrankPortman if the example isn't working with the latest dev version feel free to reopen.
