### ISSUE TITLE
@post results in “404 - Resource Not Found”

### ISSUE THREAD

**Issue by nielsenmarkus11** [trestletech/plumber#67]
I tried replicating part of the example on this [page](http://plumber.trestletech.com/docs/endpoints/).  However, when I try the `http://my-host:8000/input?val=1` it gives me the error `{"error":["404 - Resource Not Found"]}`

Am I missing anything?

**plumb-test.R**

    mylist <- 15
    
    #* @post /input
    function(val, res){
      v <- as.numeric(val)
      if (is.na(v)){
        res$status <- 400
        res$body <- "val parameter must be a number"
        return(res)
      }
      mylist <<- c(mylist,val)
    
      list(result="success")
    }

**Comment by FvD** [comment]
I tried you code and it works fine as long as you send your post request using curl:

     curl -X POST http://localhost:9080/input -d '{"val":50}' 

There is a [discussion here] about sending post requests through the browser, and people have built browser extensions to deal with this (e.g. [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop)), should that be more comfortable for you than using cURL.

**Comment by nielsenmarkus11** [comment]
Hmmm... Thanks there must be something internal that is blocking the POST.  I used your code and put it in a wrapper to ask for proxy credentials, and I got an internal error.

Thanks for your help.

**Comment by jhalagaiah** [comment]
Even I am facing the same issue. I tried in postman as well, but getting "Resource not found" error. Please help.

**Comment by nielsenmarkus11** [comment]
@jhalagaiah, you should be able to use curl on windows through the command prompt. I am also on windows.

**Comment by vikasavnish** [comment]
In general you will not find any issue. When try to run plumber behind nginx proxy, this issue frustrate .

[Solution](https://www.servloci.com/r-plumber-error-404-resource-not-found-solution/) is simple :
