### ISSUE TITLE
Question: how do I access correctly the request headers (i.e. Referer, User-Agent)?

### ISSUE THREAD

**Issue by Rainer-Kempkes** [trestletech/plumber#72]
hi,

I use plumber for a REST API and I want to access some request headers like Referer and User-Agent. I tried many alternatives in accessing it but failed desperately (i.e. req$Referer, req$REFERER, req$headers$referer and so on).
Since I didn't find any code examples on github or google, could you show me the correct way to do it?
regards,
Rainer

**Comment by trestletech** [comment]
Sorry the docs aren't very good on this. The header should be available at `req$HTTP_REFERER`. (This follows the rook specifications). 

In the future, you can always `browser()` or just `print(req)` to see what all exists on your request object as it passes through some endpoint.
