### ISSUE TITLE
plumber stripping `+` characters from request bodies

### ISSUE THREAD

**Issue by trestletech** [trestletech/plumber#81]
@pietervosnl claims in #78 that the `+` character is being stripped from JSON POST bodies.

**Comment by pietervosnl** [comment]
Sure, the '+' character is stripped when you post the following JSON string:
{"dataJSON":[{"DCE":"+"}]}

does that suffice?

**Comment by trestletech** [comment]
I wasn't able to repro using the example you provided but I did observe the substitution in a query string. #98 fixes the issue I saw. Please reppennif you're still seeing problems.
