### ISSUE TITLE
Question: is it possible to create a session-surviving cookie with plumber?

### ISSUE THREAD

**Issue by Rainer-Kempkes** [trestletech/plumber#87]
Hi  Jeff, 
first I want to thank you for the plumber package - really great work!! 
Is it possible to create a cookie with plumber that survives the current session in order to store f.e. something like a permanent visitor-id to track returning users?

Currently I create session cookies with
`r$addGlobalProcessor(sessionCookie( "mySecret", "myCookie"))`
regards,
Rainer

**Comment by trestletech** [comment]
It is not at the moment, but now that you remind me that seems like a pretty gross omission. 

I have a TODO for it here: https://github.com/trestletech/plumber/blob/c82f6b3418858b07c6ea60f19c175967fc6fd708/R/response.R#L37

It wouldn't be too painful to add this as a parameter to `setCookie` and `cookieToStr` but I'm not sure when I'd be able to get to it.

PRs welcome!
