### ISSUE TITLE
do_configure_https can't detect floating IPs assigned

### ISSUE THREAD

**Issue by trestletech** [trestletech/plumber#92]
And/or the droplet should be automatically refreshed before checking.

But when I assign a floating IP to a droplet, I have to set `force=TRUE` to get past the nslookup issue.

**Comment by vfulco** [comment]
For clarification, are you referencing the floating IP specifically?  I ask because I have one assigned on DO but am not using it while trying the toy "mean/sum" example and getting a '404' with no obvious errors from dokku, docker, nginx, etc.  TIA

**Comment by vfulco** [comment]
Ah ignore what I posted above.  My issue turned out to be I needed to manually proxy port 8000 to 80.  Likely I need to re-jigger my Dockerfile.  The answer was found here if anyone has DO, dokku, plumber issues.  https://finbarrs.co/dokku/2017/08/05/deploy-express-app-with-dokku/
