### ISSUE TITLE
Question: Can I send an HTTP status code to the client at the beginning of a function call?

### ISSUE THREAD

**Issue by bochocki** [trestletech/plumber#95]
I apologize in advance if this is a naive question or confusingly written. This is my first API (thanks plumber!) and I've spent a lot of time searching for an answer but haven't managed to make much progress.

I have a function `foo()` that takes a fairly long time to run, and I have it set up as an API with `plumber`:

```r
#* @get /foo
run_foo <- function() {
  foo()
}
```
The issue I'm having is that [Slack](api.slack.com/slash-commands), the client making the API call, [requires an HTTP 200 response within 3 seconds](https://api.slack.com/slash-commands#responding_to_a_command). Since `foo()` takes so long to run, the client posts an error message even though the code is being executed correctly. 

It seems like `plumber` returns a 200 status code once `run_foo()` completes, since replacing `foo()` with code that completes quickly (e.g., `print("hello world")`) does not return an error. Is there any way to return a status code 200 before `run_foo()` finishes? Maybe something like:

```r
#* @get /foo
run_foo <- function() {
  return_status_code("200")
  foo()
}
```

**Comment by trestletech** [comment]
Unfortunately you need plumber to respond quickly and then have some work go on in the background.

The simplest way to do this is to spin up another process that's going to do some work. e.g.

```
#* @get /foo
run_foo <- function() {
  system("Rscript -e 'myscript.R' &") 
  return_status_code("200")
}
```

or something like that. That would spawn off a new R process that's going to do some work asynchronously but respond immediately to close out the request.

The "cleaner" way to do this inside of R is just to fork and have another process start doing some things for you. Unfortunately the last time I poked at this I believe that httpuv was getting confused about having two open processes trying to handle the same request. I remember getting stuck in a couple of places with that and never had a chance to pick it back up, but YMMV.

**Comment by bochocki** [comment]
Thanks Jeff! Sorry it took so long to get back to you. I found a relatively clean solution that I'm satisfied with and seems to be working for my situation. I think it's similar to the forking solution that you proposed.

In the end, I wrote a function that uses `curl` to make an asynchronous request to another `plumber` endpoint given the original request and a forwarding URL. The function then cancels (i.e., stops waiting for) the pending asynchronous request immediately after making it:
```R
forward_request <- function(forward_url, request) { 
  h <- curl::new_handle(url = URLencode(paste0(forward_url, request))) 
  curl::multi_add(h)
  curl::multi_run(timeout = 0)
  curl::multi_cancel(h) 
}
```
I call this function in my `/foo` endpoint to transfer the request to a new endpoint, `/real_foo`, which does all the legwork, allowing `/foo` to respond to Slack quickly. My R script, then, looks like this:
```R
#* @get /foo
run_foo <- function(request) {
  forward_request("http://123.456.789.012:4242/real_foo", request)
  return("Running some code, please wait.")
}

#* @get /real_foo
run_real_foo <- function(request) {
  foo(request)
}
```
One issue, I think, is that since `/real_foo` was called by `/foo` and not by Slack, `plumber` won't send any output to Slack. Fortunately, Slack provides a response URL in the request, so I can POST any output back to the right place.

Plumber has enabled me to do all sorts of cool things in R that, until a few weeks ago, I had no idea R could do. Thanks again!

**Comment by trestletech** [comment]
Oh, great! That's a creative solution; I hadn't though of that.

Glad you're finding plumber to be useful!
